/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ServiceStandardErrorRespModel,
  V0BuildRequestListResponseModel,
  V0BuildRequestUpdateParams,
  V0BuildRequestUpdateResponseModel,
} from '../models/index';
import {
    ServiceStandardErrorRespModelFromJSON,
    ServiceStandardErrorRespModelToJSON,
    V0BuildRequestListResponseModelFromJSON,
    V0BuildRequestListResponseModelToJSON,
    V0BuildRequestUpdateParamsFromJSON,
    V0BuildRequestUpdateParamsToJSON,
    V0BuildRequestUpdateResponseModelFromJSON,
    V0BuildRequestUpdateResponseModelToJSON,
} from '../models/index';

export interface BuildRequestListRequest {
    appSlug: string;
}

export interface BuildRequestUpdateRequest {
    appSlug: string;
    buildRequestSlug: string;
    buildRequest: V0BuildRequestUpdateParams;
}

/**
 * 
 */
export class BuildRequestApi extends runtime.BaseAPI {

    /**
     * List the existing open build requests of a specified Bitrise app
     * List the open build requests for an app
     */
    async buildRequestListRaw(requestParameters: BuildRequestListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V0BuildRequestListResponseModel>> {
        if (requestParameters['appSlug'] == null) {
            throw new runtime.RequiredError(
                'appSlug',
                'Required parameter "appSlug" was null or undefined when calling buildRequestList().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Bitrise-Addon-Auth-Token"] = await this.configuration.apiKey("Bitrise-Addon-Auth-Token"); // AddonAuthToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PersonalAccessToken authentication
        }

        const response = await this.request({
            path: `/apps/{app-slug}/build-requests`.replace(`{${"app-slug"}}`, encodeURIComponent(String(requestParameters['appSlug']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V0BuildRequestListResponseModelFromJSON(jsonValue));
    }

    /**
     * List the existing open build requests of a specified Bitrise app
     * List the open build requests for an app
     */
    async buildRequestList(requestParameters: BuildRequestListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V0BuildRequestListResponseModel> {
        const response = await this.buildRequestListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update a specific build request of a specific app
     * Update a build request
     */
    async buildRequestUpdateRaw(requestParameters: BuildRequestUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<V0BuildRequestUpdateResponseModel>> {
        if (requestParameters['appSlug'] == null) {
            throw new runtime.RequiredError(
                'appSlug',
                'Required parameter "appSlug" was null or undefined when calling buildRequestUpdate().'
            );
        }

        if (requestParameters['buildRequestSlug'] == null) {
            throw new runtime.RequiredError(
                'buildRequestSlug',
                'Required parameter "buildRequestSlug" was null or undefined when calling buildRequestUpdate().'
            );
        }

        if (requestParameters['buildRequest'] == null) {
            throw new runtime.RequiredError(
                'buildRequest',
                'Required parameter "buildRequest" was null or undefined when calling buildRequestUpdate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PersonalAccessToken authentication
        }

        const response = await this.request({
            path: `/apps/{app-slug}/build-requests/{build-request-slug}`.replace(`{${"app-slug"}}`, encodeURIComponent(String(requestParameters['appSlug']))).replace(`{${"build-request-slug"}}`, encodeURIComponent(String(requestParameters['buildRequestSlug']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: V0BuildRequestUpdateParamsToJSON(requestParameters['buildRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => V0BuildRequestUpdateResponseModelFromJSON(jsonValue));
    }

    /**
     * Update a specific build request of a specific app
     * Update a build request
     */
    async buildRequestUpdate(requestParameters: BuildRequestUpdateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<V0BuildRequestUpdateResponseModel> {
        const response = await this.buildRequestUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
