/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppRolesQuery200Response
 */
export interface AppRolesQuery200Response {
    /**
     * 
     * @type {Array<string>}
     * @memberof AppRolesQuery200Response
     */
    groups?: Array<string>;
}

/**
 * Check if a given object implements the AppRolesQuery200Response interface.
 */
export function instanceOfAppRolesQuery200Response(value: object): value is AppRolesQuery200Response {
    return true;
}

export function AppRolesQuery200ResponseFromJSON(json: any): AppRolesQuery200Response {
    return AppRolesQuery200ResponseFromJSONTyped(json, false);
}

export function AppRolesQuery200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppRolesQuery200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'groups': json['groups'] == null ? undefined : json['groups'],
    };
}

export function AppRolesQuery200ResponseToJSON(json: any): AppRolesQuery200Response {
    return AppRolesQuery200ResponseToJSONTyped(json, false);
}

export function AppRolesQuery200ResponseToJSONTyped(value?: AppRolesQuery200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'groups': value['groups'],
    };
}

