/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppSecretUpdateRequest
 */
export interface AppSecretUpdateRequest {
    /**
     * 
     * @type {boolean}
     * @memberof AppSecretUpdateRequest
     */
    expandInStepInputs?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AppSecretUpdateRequest
     */
    isExposedForPullRequests?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AppSecretUpdateRequest
     */
    isProtected?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AppSecretUpdateRequest
     */
    value?: string;
}

/**
 * Check if a given object implements the AppSecretUpdateRequest interface.
 */
export function instanceOfAppSecretUpdateRequest(value: object): value is AppSecretUpdateRequest {
    return true;
}

export function AppSecretUpdateRequestFromJSON(json: any): AppSecretUpdateRequest {
    return AppSecretUpdateRequestFromJSONTyped(json, false);
}

export function AppSecretUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppSecretUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'expandInStepInputs': json['expand_in_step_inputs'] == null ? undefined : json['expand_in_step_inputs'],
        'isExposedForPullRequests': json['is_exposed_for_pull_requests'] == null ? undefined : json['is_exposed_for_pull_requests'],
        'isProtected': json['is_protected'] == null ? undefined : json['is_protected'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function AppSecretUpdateRequestToJSON(json: any): AppSecretUpdateRequest {
    return AppSecretUpdateRequestToJSONTyped(json, false);
}

export function AppSecretUpdateRequestToJSONTyped(value?: AppSecretUpdateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'expand_in_step_inputs': value['expandInStepInputs'],
        'is_exposed_for_pull_requests': value['isExposedForPullRequests'],
        'is_protected': value['isProtected'],
        'value': value['value'],
    };
}

