/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AppSecretsShow200Response
 */
export interface AppSecretsShow200Response {
    /**
     * 
     * @type {boolean}
     * @memberof AppSecretsShow200Response
     */
    expandInStepInputs?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AppSecretsShow200Response
     */
    id?: string;
    /**
     * 
     * @type {boolean}
     * @memberof AppSecretsShow200Response
     */
    isExposedForPullRequests?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AppSecretsShow200Response
     */
    isProtected?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AppSecretsShow200Response
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof AppSecretsShow200Response
     */
    scope?: string;
    /**
     * 
     * @type {string}
     * @memberof AppSecretsShow200Response
     */
    value?: string;
}

/**
 * Check if a given object implements the AppSecretsShow200Response interface.
 */
export function instanceOfAppSecretsShow200Response(value: object): value is AppSecretsShow200Response {
    return true;
}

export function AppSecretsShow200ResponseFromJSON(json: any): AppSecretsShow200Response {
    return AppSecretsShow200ResponseFromJSONTyped(json, false);
}

export function AppSecretsShow200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AppSecretsShow200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'expandInStepInputs': json['expand_in_step_inputs'] == null ? undefined : json['expand_in_step_inputs'],
        'id': json['id'] == null ? undefined : json['id'],
        'isExposedForPullRequests': json['is_exposed_for_pull_requests'] == null ? undefined : json['is_exposed_for_pull_requests'],
        'isProtected': json['is_protected'] == null ? undefined : json['is_protected'],
        'name': json['name'] == null ? undefined : json['name'],
        'scope': json['scope'] == null ? undefined : json['scope'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function AppSecretsShow200ResponseToJSON(json: any): AppSecretsShow200Response {
    return AppSecretsShow200ResponseToJSONTyped(json, false);
}

export function AppSecretsShow200ResponseToJSONTyped(value?: AppSecretsShow200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'expand_in_step_inputs': value['expandInStepInputs'],
        'id': value['id'],
        'is_exposed_for_pull_requests': value['isExposedForPullRequests'],
        'is_protected': value['isProtected'],
        'name': value['name'],
        'scope': value['scope'],
        'value': value['value'],
    };
}

