/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GroupMemberAddRequest
 */
export interface GroupMemberAddRequest {
    /**
     * user slug
     * @type {string}
     * @memberof GroupMemberAddRequest
     */
    userId?: string;
}

/**
 * Check if a given object implements the GroupMemberAddRequest interface.
 */
export function instanceOfGroupMemberAddRequest(value: object): value is GroupMemberAddRequest {
    return true;
}

export function GroupMemberAddRequestFromJSON(json: any): GroupMemberAddRequest {
    return GroupMemberAddRequestFromJSONTyped(json, false);
}

export function GroupMemberAddRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupMemberAddRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userId': json['user_id'] == null ? undefined : json['user_id'],
    };
}

export function GroupMemberAddRequestToJSON(json: any): GroupMemberAddRequest {
    return GroupMemberAddRequestToJSONTyped(json, false);
}

export function GroupMemberAddRequestToJSONTyped(value?: GroupMemberAddRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'user_id': value['userId'],
    };
}

