/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MemberAddRequest
 */
export interface MemberAddRequest {
    /**
     * 
     * @type {string}
     * @memberof MemberAddRequest
     */
    email?: string;
}

/**
 * Check if a given object implements the MemberAddRequest interface.
 */
export function instanceOfMemberAddRequest(value: object): value is MemberAddRequest {
    return true;
}

export function MemberAddRequestFromJSON(json: any): MemberAddRequest {
    return MemberAddRequestFromJSONTyped(json, false);
}

export function MemberAddRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MemberAddRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
    };
}

export function MemberAddRequestToJSON(json: any): MemberAddRequest {
    return MemberAddRequestToJSONTyped(json, false);
}

export function MemberAddRequestToJSONTyped(value?: MemberAddRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
    };
}

