/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizationSecretCreateRequest
 */
export interface OrganizationSecretCreateRequest {
    /**
     * 
     * @type {boolean}
     * @memberof OrganizationSecretCreateRequest
     */
    expandInStepInputs?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OrganizationSecretCreateRequest
     */
    isExposedForPullRequests?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof OrganizationSecretCreateRequest
     */
    isProtected?: boolean;
    /**
     * 
     * @type {string}
     * @memberof OrganizationSecretCreateRequest
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationSecretCreateRequest
     */
    scope?: string;
    /**
     * 
     * @type {string}
     * @memberof OrganizationSecretCreateRequest
     */
    value: string;
}

/**
 * Check if a given object implements the OrganizationSecretCreateRequest interface.
 */
export function instanceOfOrganizationSecretCreateRequest(value: object): value is OrganizationSecretCreateRequest {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    return true;
}

export function OrganizationSecretCreateRequestFromJSON(json: any): OrganizationSecretCreateRequest {
    return OrganizationSecretCreateRequestFromJSONTyped(json, false);
}

export function OrganizationSecretCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationSecretCreateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'expandInStepInputs': json['expand_in_step_inputs'] == null ? undefined : json['expand_in_step_inputs'],
        'isExposedForPullRequests': json['is_exposed_for_pull_requests'] == null ? undefined : json['is_exposed_for_pull_requests'],
        'isProtected': json['is_protected'] == null ? undefined : json['is_protected'],
        'name': json['name'],
        'scope': json['scope'] == null ? undefined : json['scope'],
        'value': json['value'],
    };
}

export function OrganizationSecretCreateRequestToJSON(json: any): OrganizationSecretCreateRequest {
    return OrganizationSecretCreateRequestToJSONTyped(json, false);
}

export function OrganizationSecretCreateRequestToJSONTyped(value?: OrganizationSecretCreateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'expand_in_step_inputs': value['expandInStepInputs'],
        'is_exposed_for_pull_requests': value['isExposedForPullRequests'],
        'is_protected': value['isProtected'],
        'name': value['name'],
        'scope': value['scope'],
        'value': value['value'],
    };
}

