/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrganizationGroupAddRequest
 */
export interface OrganizationGroupAddRequest {
    /**
     * 
     * @type {string}
     * @memberof OrganizationGroupAddRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the OrganizationGroupAddRequest interface.
 */
export function instanceOfOrganizationGroupAddRequest(value: object): value is OrganizationGroupAddRequest {
    return true;
}

export function OrganizationGroupAddRequestFromJSON(json: any): OrganizationGroupAddRequest {
    return OrganizationGroupAddRequestFromJSONTyped(json, false);
}

export function OrganizationGroupAddRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrganizationGroupAddRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function OrganizationGroupAddRequestToJSON(json: any): OrganizationGroupAddRequest {
    return OrganizationGroupAddRequestToJSONTyped(json, false);
}

export function OrganizationGroupAddRequestToJSONTyped(value?: OrganizationGroupAddRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
    };
}

