/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PipelineabledomainEnvironments
 */
export interface PipelineabledomainEnvironments {
    /**
     * 
     * @type {object}
     * @memberof PipelineabledomainEnvironments
     */
    isExpand?: object;
    /**
     * 
     * @type {string}
     * @memberof PipelineabledomainEnvironments
     */
    key?: string;
    /**
     * 
     * @type {object}
     * @memberof PipelineabledomainEnvironments
     */
    value?: object;
}

/**
 * Check if a given object implements the PipelineabledomainEnvironments interface.
 */
export function instanceOfPipelineabledomainEnvironments(value: object): value is PipelineabledomainEnvironments {
    return true;
}

export function PipelineabledomainEnvironmentsFromJSON(json: any): PipelineabledomainEnvironments {
    return PipelineabledomainEnvironmentsFromJSONTyped(json, false);
}

export function PipelineabledomainEnvironmentsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PipelineabledomainEnvironments {
    if (json == null) {
        return json;
    }
    return {
        
        'isExpand': json['is_expand'] == null ? undefined : json['is_expand'],
        'key': json['key'] == null ? undefined : json['key'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function PipelineabledomainEnvironmentsToJSON(json: any): PipelineabledomainEnvironments {
    return PipelineabledomainEnvironmentsToJSONTyped(json, false);
}

export function PipelineabledomainEnvironmentsToJSONTyped(value?: PipelineabledomainEnvironments | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'is_expand': value['isExpand'],
        'key': value['key'],
        'value': value['value'],
    };
}

