/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PipelineabledomainEnvironments } from './PipelineabledomainEnvironments';
import {
    PipelineabledomainEnvironmentsFromJSON,
    PipelineabledomainEnvironmentsFromJSONTyped,
    PipelineabledomainEnvironmentsToJSON,
    PipelineabledomainEnvironmentsToJSONTyped,
} from './PipelineabledomainEnvironments';

/**
 * 
 * @export
 * @interface PipelineabledomainTriggerParams
 */
export interface PipelineabledomainTriggerParams {
    /**
     * 
     * @type {string}
     * @memberof PipelineabledomainTriggerParams
     */
    branch?: string;
    /**
     * 
     * @type {string}
     * @memberof PipelineabledomainTriggerParams
     */
    branchDest?: string;
    /**
     * 
     * @type {string}
     * @memberof PipelineabledomainTriggerParams
     */
    branchDestRepoOwner?: string;
    /**
     * 
     * @type {string}
     * @memberof PipelineabledomainTriggerParams
     */
    branchRepoOwner?: string;
    /**
     * 
     * @type {string}
     * @memberof PipelineabledomainTriggerParams
     */
    commitHash?: string;
    /**
     * 
     * @type {string}
     * @memberof PipelineabledomainTriggerParams
     */
    commitMessage?: string;
    /**
     * 
     * @type {Array<PipelineabledomainEnvironments>}
     * @memberof PipelineabledomainTriggerParams
     */
    environments?: Array<PipelineabledomainEnvironments>;
    /**
     * 
     * @type {string}
     * @memberof PipelineabledomainTriggerParams
     */
    machineTypeId?: string;
    /**
     * 
     * @type {string}
     * @memberof PipelineabledomainTriggerParams
     */
    pullRequestAuthor?: string;
    /**
     * 
     * @type {string}
     * @memberof PipelineabledomainTriggerParams
     */
    pullRequestHeadBranch?: string;
    /**
     * 
     * @type {object}
     * @memberof PipelineabledomainTriggerParams
     */
    pullRequestId?: object;
    /**
     * 
     * @type {string}
     * @memberof PipelineabledomainTriggerParams
     */
    pullRequestMergeBranch?: string;
    /**
     * 
     * @type {string}
     * @memberof PipelineabledomainTriggerParams
     */
    pullRequestRepositoryUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof PipelineabledomainTriggerParams
     */
    pullRequestUnverifiedMergeBranch?: string;
    /**
     * 
     * @type {string}
     * @memberof PipelineabledomainTriggerParams
     */
    stack?: string;
    /**
     * 
     * @type {object}
     * @memberof PipelineabledomainTriggerParams
     */
    tag?: object;
}

/**
 * Check if a given object implements the PipelineabledomainTriggerParams interface.
 */
export function instanceOfPipelineabledomainTriggerParams(value: object): value is PipelineabledomainTriggerParams {
    return true;
}

export function PipelineabledomainTriggerParamsFromJSON(json: any): PipelineabledomainTriggerParams {
    return PipelineabledomainTriggerParamsFromJSONTyped(json, false);
}

export function PipelineabledomainTriggerParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PipelineabledomainTriggerParams {
    if (json == null) {
        return json;
    }
    return {
        
        'branch': json['branch'] == null ? undefined : json['branch'],
        'branchDest': json['branch_dest'] == null ? undefined : json['branch_dest'],
        'branchDestRepoOwner': json['branch_dest_repo_owner'] == null ? undefined : json['branch_dest_repo_owner'],
        'branchRepoOwner': json['branch_repo_owner'] == null ? undefined : json['branch_repo_owner'],
        'commitHash': json['commit_hash'] == null ? undefined : json['commit_hash'],
        'commitMessage': json['commit_message'] == null ? undefined : json['commit_message'],
        'environments': json['environments'] == null ? undefined : ((json['environments'] as Array<any>).map(PipelineabledomainEnvironmentsFromJSON)),
        'machineTypeId': json['machine_type_id'] == null ? undefined : json['machine_type_id'],
        'pullRequestAuthor': json['pull_request_author'] == null ? undefined : json['pull_request_author'],
        'pullRequestHeadBranch': json['pull_request_head_branch'] == null ? undefined : json['pull_request_head_branch'],
        'pullRequestId': json['pull_request_id'] == null ? undefined : json['pull_request_id'],
        'pullRequestMergeBranch': json['pull_request_merge_branch'] == null ? undefined : json['pull_request_merge_branch'],
        'pullRequestRepositoryUrl': json['pull_request_repository_url'] == null ? undefined : json['pull_request_repository_url'],
        'pullRequestUnverifiedMergeBranch': json['pull_request_unverified_merge_branch'] == null ? undefined : json['pull_request_unverified_merge_branch'],
        'stack': json['stack'] == null ? undefined : json['stack'],
        'tag': json['tag'] == null ? undefined : json['tag'],
    };
}

export function PipelineabledomainTriggerParamsToJSON(json: any): PipelineabledomainTriggerParams {
    return PipelineabledomainTriggerParamsToJSONTyped(json, false);
}

export function PipelineabledomainTriggerParamsToJSONTyped(value?: PipelineabledomainTriggerParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'branch': value['branch'],
        'branch_dest': value['branchDest'],
        'branch_dest_repo_owner': value['branchDestRepoOwner'],
        'branch_repo_owner': value['branchRepoOwner'],
        'commit_hash': value['commitHash'],
        'commit_message': value['commitMessage'],
        'environments': value['environments'] == null ? undefined : ((value['environments'] as Array<any>).map(PipelineabledomainEnvironmentsToJSON)),
        'machine_type_id': value['machineTypeId'],
        'pull_request_author': value['pullRequestAuthor'],
        'pull_request_head_branch': value['pullRequestHeadBranch'],
        'pull_request_id': value['pullRequestId'],
        'pull_request_merge_branch': value['pullRequestMergeBranch'],
        'pull_request_repository_url': value['pullRequestRepositoryUrl'],
        'pull_request_unverified_merge_branch': value['pullRequestUnverifiedMergeBranch'],
        'stack': value['stack'],
        'tag': value['tag'],
    };
}

