/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SecretValueGet200Response
 */
export interface SecretValueGet200Response {
    /**
     * 
     * @type {string}
     * @memberof SecretValueGet200Response
     */
    value?: string;
}

/**
 * Check if a given object implements the SecretValueGet200Response interface.
 */
export function instanceOfSecretValueGet200Response(value: object): value is SecretValueGet200Response {
    return true;
}

export function SecretValueGet200ResponseFromJSON(json: any): SecretValueGet200Response {
    return SecretValueGet200ResponseFromJSONTyped(json, false);
}

export function SecretValueGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SecretValueGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function SecretValueGet200ResponseToJSON(json: any): SecretValueGet200Response {
    return SecretValueGet200ResponseToJSONTyped(json, false);
}

export function SecretValueGet200ResponseToJSONTyped(value?: SecretValueGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'value': value['value'],
    };
}

