/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ServiceDtoCreatedSecretNoValue } from './ServiceDtoCreatedSecretNoValue';
import {
    ServiceDtoCreatedSecretNoValueFromJSON,
    ServiceDtoCreatedSecretNoValueFromJSONTyped,
    ServiceDtoCreatedSecretNoValueToJSON,
    ServiceDtoCreatedSecretNoValueToJSONTyped,
} from './ServiceDtoCreatedSecretNoValue';

/**
 * 
 * @export
 * @interface SecretList200Response
 */
export interface SecretList200Response {
    /**
     * 
     * @type {Array<ServiceDtoCreatedSecretNoValue>}
     * @memberof SecretList200Response
     */
    secrets?: Array<ServiceDtoCreatedSecretNoValue>;
}

/**
 * Check if a given object implements the SecretList200Response interface.
 */
export function instanceOfSecretList200Response(value: object): value is SecretList200Response {
    return true;
}

export function SecretList200ResponseFromJSON(json: any): SecretList200Response {
    return SecretList200ResponseFromJSONTyped(json, false);
}

export function SecretList200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SecretList200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'secrets': json['secrets'] == null ? undefined : ((json['secrets'] as Array<any>).map(ServiceDtoCreatedSecretNoValueFromJSON)),
    };
}

export function SecretList200ResponseToJSON(json: any): SecretList200Response {
    return SecretList200ResponseToJSONTyped(json, false);
}

export function SecretList200ResponseToJSONTyped(value?: SecretList200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'secrets': value['secrets'] == null ? undefined : ((value['secrets'] as Array<any>).map(ServiceDtoCreatedSecretNoValueToJSON)),
    };
}

