/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServiceDtoMember
 */
export interface ServiceDtoMember {
    /**
     * 
     * @type {string}
     * @memberof ServiceDtoMember
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceDtoMember
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceDtoMember
     */
    username?: string;
}

/**
 * Check if a given object implements the ServiceDtoMember interface.
 */
export function instanceOfServiceDtoMember(value: object): value is ServiceDtoMember {
    return true;
}

export function ServiceDtoMemberFromJSON(json: any): ServiceDtoMember {
    return ServiceDtoMemberFromJSONTyped(json, false);
}

export function ServiceDtoMemberFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceDtoMember {
    if (json == null) {
        return json;
    }
    return {
        
        'email': json['email'] == null ? undefined : json['email'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'username': json['username'] == null ? undefined : json['username'],
    };
}

export function ServiceDtoMemberToJSON(json: any): ServiceDtoMember {
    return ServiceDtoMemberToJSONTyped(json, false);
}

export function ServiceDtoMemberToJSONTyped(value?: ServiceDtoMember | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'email': value['email'],
        'slug': value['slug'],
        'username': value['username'],
    };
}

