/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServiceDtoCreatedSecretNoValue
 */
export interface ServiceDtoCreatedSecretNoValue {
    /**
     * 
     * @type {boolean}
     * @memberof ServiceDtoCreatedSecretNoValue
     */
    expandInStepInputs?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ServiceDtoCreatedSecretNoValue
     */
    id?: string;
    /**
     * 
     * @type {boolean}
     * @memberof ServiceDtoCreatedSecretNoValue
     */
    isExposedForPullRequests?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ServiceDtoCreatedSecretNoValue
     */
    isProtected?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ServiceDtoCreatedSecretNoValue
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceDtoCreatedSecretNoValue
     */
    scope?: string;
}

/**
 * Check if a given object implements the ServiceDtoCreatedSecretNoValue interface.
 */
export function instanceOfServiceDtoCreatedSecretNoValue(value: object): value is ServiceDtoCreatedSecretNoValue {
    return true;
}

export function ServiceDtoCreatedSecretNoValueFromJSON(json: any): ServiceDtoCreatedSecretNoValue {
    return ServiceDtoCreatedSecretNoValueFromJSONTyped(json, false);
}

export function ServiceDtoCreatedSecretNoValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceDtoCreatedSecretNoValue {
    if (json == null) {
        return json;
    }
    return {
        
        'expandInStepInputs': json['expand_in_step_inputs'] == null ? undefined : json['expand_in_step_inputs'],
        'id': json['id'] == null ? undefined : json['id'],
        'isExposedForPullRequests': json['is_exposed_for_pull_requests'] == null ? undefined : json['is_exposed_for_pull_requests'],
        'isProtected': json['is_protected'] == null ? undefined : json['is_protected'],
        'name': json['name'] == null ? undefined : json['name'],
        'scope': json['scope'] == null ? undefined : json['scope'],
    };
}

export function ServiceDtoCreatedSecretNoValueToJSON(json: any): ServiceDtoCreatedSecretNoValue {
    return ServiceDtoCreatedSecretNoValueToJSONTyped(json, false);
}

export function ServiceDtoCreatedSecretNoValueToJSONTyped(value?: ServiceDtoCreatedSecretNoValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'expand_in_step_inputs': value['expandInStepInputs'],
        'id': value['id'],
        'is_exposed_for_pull_requests': value['isExposedForPullRequests'],
        'is_protected': value['isProtected'],
        'name': value['name'],
        'scope': value['scope'],
    };
}

