/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServiceDtoGroup
 */
export interface ServiceDtoGroup {
    /**
     * 
     * @type {string}
     * @memberof ServiceDtoGroup
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceDtoGroup
     */
    slug?: string;
}

/**
 * Check if a given object implements the ServiceDtoGroup interface.
 */
export function instanceOfServiceDtoGroup(value: object): value is ServiceDtoGroup {
    return true;
}

export function ServiceDtoGroupFromJSON(json: any): ServiceDtoGroup {
    return ServiceDtoGroupFromJSONTyped(json, false);
}

export function ServiceDtoGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceDtoGroup {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'slug': json['slug'] == null ? undefined : json['slug'],
    };
}

export function ServiceDtoGroupToJSON(json: any): ServiceDtoGroup {
    return ServiceDtoGroupToJSONTyped(json, false);
}

export function ServiceDtoGroupToJSONTyped(value?: ServiceDtoGroup | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'slug': value['slug'],
    };
}

