/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V0PagingResponseModel } from './V0PagingResponseModel';
import {
    V0PagingResponseModelFromJSON,
    V0PagingResponseModelFromJSONTyped,
    V0PagingResponseModelToJSON,
    V0PagingResponseModelToJSONTyped,
} from './V0PagingResponseModel';
import type { V0ActivityEventResponseItemModel } from './V0ActivityEventResponseItemModel';
import {
    V0ActivityEventResponseItemModelFromJSON,
    V0ActivityEventResponseItemModelFromJSONTyped,
    V0ActivityEventResponseItemModelToJSON,
    V0ActivityEventResponseItemModelToJSONTyped,
} from './V0ActivityEventResponseItemModel';

/**
 * 
 * @export
 * @interface V0ActivityEventListResponseModel
 */
export interface V0ActivityEventListResponseModel {
    /**
     * 
     * @type {Array<V0ActivityEventResponseItemModel>}
     * @memberof V0ActivityEventListResponseModel
     */
    data?: Array<V0ActivityEventResponseItemModel>;
    /**
     * 
     * @type {V0PagingResponseModel}
     * @memberof V0ActivityEventListResponseModel
     */
    paging?: V0PagingResponseModel;
}

/**
 * Check if a given object implements the V0ActivityEventListResponseModel interface.
 */
export function instanceOfV0ActivityEventListResponseModel(value: object): value is V0ActivityEventListResponseModel {
    return true;
}

export function V0ActivityEventListResponseModelFromJSON(json: any): V0ActivityEventListResponseModel {
    return V0ActivityEventListResponseModelFromJSONTyped(json, false);
}

export function V0ActivityEventListResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0ActivityEventListResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(V0ActivityEventResponseItemModelFromJSON)),
        'paging': json['paging'] == null ? undefined : V0PagingResponseModelFromJSON(json['paging']),
    };
}

export function V0ActivityEventListResponseModelToJSON(json: any): V0ActivityEventListResponseModel {
    return V0ActivityEventListResponseModelToJSONTyped(json, false);
}

export function V0ActivityEventListResponseModelToJSONTyped(value?: V0ActivityEventListResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(V0ActivityEventResponseItemModelToJSON)),
        'paging': V0PagingResponseModelToJSON(value['paging']),
    };
}

