/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AddonsAddon } from './AddonsAddon';
import {
    AddonsAddonFromJSON,
    AddonsAddonFromJSONTyped,
    AddonsAddonToJSON,
    AddonsAddonToJSONTyped,
} from './AddonsAddon';

/**
 * 
 * @export
 * @interface V0AddonsShowResponseModel
 */
export interface V0AddonsShowResponseModel {
    /**
     * 
     * @type {AddonsAddon}
     * @memberof V0AddonsShowResponseModel
     */
    data?: AddonsAddon;
}

/**
 * Check if a given object implements the V0AddonsShowResponseModel interface.
 */
export function instanceOfV0AddonsShowResponseModel(value: object): value is V0AddonsShowResponseModel {
    return true;
}

export function V0AddonsShowResponseModelFromJSON(json: any): V0AddonsShowResponseModel {
    return V0AddonsShowResponseModelFromJSONTyped(json, false);
}

export function V0AddonsShowResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0AddonsShowResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : AddonsAddonFromJSON(json['data']),
    };
}

export function V0AddonsShowResponseModelToJSON(json: any): V0AddonsShowResponseModel {
    return V0AddonsShowResponseModelToJSONTyped(json, false);
}

export function V0AddonsShowResponseModelToJSONTyped(value?: V0AddonsShowResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': AddonsAddonToJSON(value['data']),
    };
}

