/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V0AndroidKeystoreFileUploadParams
 */
export interface V0AndroidKeystoreFileUploadParams {
    /**
     * 
     * @type {string}
     * @memberof V0AndroidKeystoreFileUploadParams
     */
    alias: string;
    /**
     * 
     * @type {string}
     * @memberof V0AndroidKeystoreFileUploadParams
     */
    keystoreFileName?: string;
    /**
     * 
     * @type {string}
     * @memberof V0AndroidKeystoreFileUploadParams
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof V0AndroidKeystoreFileUploadParams
     */
    privateKeyPassword: string;
    /**
     * 
     * @type {string}
     * @memberof V0AndroidKeystoreFileUploadParams
     */
    uploadFileName: string;
    /**
     * 
     * @type {number}
     * @memberof V0AndroidKeystoreFileUploadParams
     */
    uploadFileSize: number;
}

/**
 * Check if a given object implements the V0AndroidKeystoreFileUploadParams interface.
 */
export function instanceOfV0AndroidKeystoreFileUploadParams(value: object): value is V0AndroidKeystoreFileUploadParams {
    if (!('alias' in value) || value['alias'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('privateKeyPassword' in value) || value['privateKeyPassword'] === undefined) return false;
    if (!('uploadFileName' in value) || value['uploadFileName'] === undefined) return false;
    if (!('uploadFileSize' in value) || value['uploadFileSize'] === undefined) return false;
    return true;
}

export function V0AndroidKeystoreFileUploadParamsFromJSON(json: any): V0AndroidKeystoreFileUploadParams {
    return V0AndroidKeystoreFileUploadParamsFromJSONTyped(json, false);
}

export function V0AndroidKeystoreFileUploadParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0AndroidKeystoreFileUploadParams {
    if (json == null) {
        return json;
    }
    return {
        
        'alias': json['alias'],
        'keystoreFileName': json['keystore_file_name'] == null ? undefined : json['keystore_file_name'],
        'password': json['password'],
        'privateKeyPassword': json['private_key_password'],
        'uploadFileName': json['upload_file_name'],
        'uploadFileSize': json['upload_file_size'],
    };
}

export function V0AndroidKeystoreFileUploadParamsToJSON(json: any): V0AndroidKeystoreFileUploadParams {
    return V0AndroidKeystoreFileUploadParamsToJSONTyped(json, false);
}

export function V0AndroidKeystoreFileUploadParamsToJSONTyped(value?: V0AndroidKeystoreFileUploadParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'alias': value['alias'],
        'keystore_file_name': value['keystoreFileName'],
        'password': value['password'],
        'private_key_password': value['privateKeyPassword'],
        'upload_file_name': value['uploadFileName'],
        'upload_file_size': value['uploadFileSize'],
    };
}

