/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V0AppWebhookUpdateParams
 */
export interface V0AppWebhookUpdateParams {
    /**
     * 
     * @type {Array<string>}
     * @memberof V0AppWebhookUpdateParams
     */
    events: Array<string>;
    /**
     * 
     * @type {object}
     * @memberof V0AppWebhookUpdateParams
     */
    headers?: object;
    /**
     * 
     * @type {string}
     * @memberof V0AppWebhookUpdateParams
     */
    url: string;
}

/**
 * Check if a given object implements the V0AppWebhookUpdateParams interface.
 */
export function instanceOfV0AppWebhookUpdateParams(value: object): value is V0AppWebhookUpdateParams {
    if (!('events' in value) || value['events'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function V0AppWebhookUpdateParamsFromJSON(json: any): V0AppWebhookUpdateParams {
    return V0AppWebhookUpdateParamsFromJSONTyped(json, false);
}

export function V0AppWebhookUpdateParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0AppWebhookUpdateParams {
    if (json == null) {
        return json;
    }
    return {
        
        'events': json['events'],
        'headers': json['headers'] == null ? undefined : json['headers'],
        'url': json['url'],
    };
}

export function V0AppWebhookUpdateParamsToJSON(json: any): V0AppWebhookUpdateParams {
    return V0AppWebhookUpdateParamsToJSONTyped(json, false);
}

export function V0AppWebhookUpdateParamsToJSONTyped(value?: V0AppWebhookUpdateParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'events': value['events'],
        'headers': value['headers'],
        'url': value['url'],
    };
}

