/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V0AppWebhookResponseItemModel
 */
export interface V0AppWebhookResponseItemModel {
    /**
     * 
     * @type {string}
     * @memberof V0AppWebhookResponseItemModel
     */
    createdAt?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof V0AppWebhookResponseItemModel
     */
    events?: Array<string>;
    /**
     * 
     * @type {object}
     * @memberof V0AppWebhookResponseItemModel
     */
    headers?: object;
    /**
     * 
     * @type {boolean}
     * @memberof V0AppWebhookResponseItemModel
     */
    registeredByAddon?: boolean;
    /**
     * 
     * @type {string}
     * @memberof V0AppWebhookResponseItemModel
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof V0AppWebhookResponseItemModel
     */
    updatedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof V0AppWebhookResponseItemModel
     */
    url?: string;
}

/**
 * Check if a given object implements the V0AppWebhookResponseItemModel interface.
 */
export function instanceOfV0AppWebhookResponseItemModel(value: object): value is V0AppWebhookResponseItemModel {
    return true;
}

export function V0AppWebhookResponseItemModelFromJSON(json: any): V0AppWebhookResponseItemModel {
    return V0AppWebhookResponseItemModelFromJSONTyped(json, false);
}

export function V0AppWebhookResponseItemModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0AppWebhookResponseItemModel {
    if (json == null) {
        return json;
    }
    return {
        
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'events': json['events'] == null ? undefined : json['events'],
        'headers': json['headers'] == null ? undefined : json['headers'],
        'registeredByAddon': json['registered_by_addon'] == null ? undefined : json['registered_by_addon'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'updatedAt': json['updated_at'] == null ? undefined : json['updated_at'],
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function V0AppWebhookResponseItemModelToJSON(json: any): V0AppWebhookResponseItemModel {
    return V0AppWebhookResponseItemModelToJSONTyped(json, false);
}

export function V0AppWebhookResponseItemModelToJSONTyped(value?: V0AppWebhookResponseItemModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'created_at': value['createdAt'],
        'events': value['events'],
        'headers': value['headers'],
        'registered_by_addon': value['registeredByAddon'],
        'slug': value['slug'],
        'updated_at': value['updatedAt'],
        'url': value['url'],
    };
}

