/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V0AppUpdateRespModel
 */
export interface V0AppUpdateRespModel {
    /**
     * 
     * @type {string}
     * @memberof V0AppUpdateRespModel
     */
    status?: string;
}

/**
 * Check if a given object implements the V0AppUpdateRespModel interface.
 */
export function instanceOfV0AppUpdateRespModel(value: object): value is V0AppUpdateRespModel {
    return true;
}

export function V0AppUpdateRespModelFromJSON(json: any): V0AppUpdateRespModel {
    return V0AppUpdateRespModelFromJSONTyped(json, false);
}

export function V0AppUpdateRespModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0AppUpdateRespModel {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function V0AppUpdateRespModelToJSON(json: any): V0AppUpdateRespModel {
    return V0AppUpdateRespModelToJSONTyped(json, false);
}

export function V0AppUpdateRespModelToJSONTyped(value?: V0AppUpdateRespModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
    };
}

