/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V0AppWebhookResponseItemModel } from './V0AppWebhookResponseItemModel';
import {
    V0AppWebhookResponseItemModelFromJSON,
    V0AppWebhookResponseItemModelFromJSONTyped,
    V0AppWebhookResponseItemModelToJSON,
    V0AppWebhookResponseItemModelToJSONTyped,
} from './V0AppWebhookResponseItemModel';

/**
 * 
 * @export
 * @interface V0AppWebhookDeletedResponseModel
 */
export interface V0AppWebhookDeletedResponseModel {
    /**
     * 
     * @type {V0AppWebhookResponseItemModel}
     * @memberof V0AppWebhookDeletedResponseModel
     */
    data?: V0AppWebhookResponseItemModel;
}

/**
 * Check if a given object implements the V0AppWebhookDeletedResponseModel interface.
 */
export function instanceOfV0AppWebhookDeletedResponseModel(value: object): value is V0AppWebhookDeletedResponseModel {
    return true;
}

export function V0AppWebhookDeletedResponseModelFromJSON(json: any): V0AppWebhookDeletedResponseModel {
    return V0AppWebhookDeletedResponseModelFromJSONTyped(json, false);
}

export function V0AppWebhookDeletedResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0AppWebhookDeletedResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : V0AppWebhookResponseItemModelFromJSON(json['data']),
    };
}

export function V0AppWebhookDeletedResponseModelToJSON(json: any): V0AppWebhookDeletedResponseModel {
    return V0AppWebhookDeletedResponseModelToJSONTyped(json, false);
}

export function V0AppWebhookDeletedResponseModelToJSONTyped(value?: V0AppWebhookDeletedResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': V0AppWebhookResponseItemModelToJSON(value['data']),
    };
}

