/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V0AppResponseItemModel } from './V0AppResponseItemModel';
import {
    V0AppResponseItemModelFromJSON,
    V0AppResponseItemModelFromJSONTyped,
    V0AppResponseItemModelToJSON,
    V0AppResponseItemModelToJSONTyped,
} from './V0AppResponseItemModel';

/**
 * 
 * @export
 * @interface V0AppShowResponseModel
 */
export interface V0AppShowResponseModel {
    /**
     * 
     * @type {V0AppResponseItemModel}
     * @memberof V0AppShowResponseModel
     */
    data?: V0AppResponseItemModel;
}

/**
 * Check if a given object implements the V0AppShowResponseModel interface.
 */
export function instanceOfV0AppShowResponseModel(value: object): value is V0AppShowResponseModel {
    return true;
}

export function V0AppShowResponseModelFromJSON(json: any): V0AppShowResponseModel {
    return V0AppShowResponseModelFromJSONTyped(json, false);
}

export function V0AppShowResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0AppShowResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : V0AppResponseItemModelFromJSON(json['data']),
    };
}

export function V0AppShowResponseModelToJSON(json: any): V0AppShowResponseModel {
    return V0AppShowResponseModelToJSONTyped(json, false);
}

export function V0AppShowResponseModelToJSONTyped(value?: V0AppShowResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': V0AppResponseItemModelToJSON(value['data']),
    };
}

