/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V0AppUpdateParams
 */
export interface V0AppUpdateParams {
    /**
     * The new apple credential user ID (recommendation: use the UI to set this)
     * @type {number}
     * @memberof V0AppUpdateParams
     */
    appleCredentialUserId?: number;
    /**
     * The new apple credential user slug (recommendation: use the UI to set this)
     * @type {string}
     * @memberof V0AppUpdateParams
     */
    appleCredentialUserSlug?: string;
    /**
     * The new default branch for the application.
     * @type {string}
     * @memberof V0AppUpdateParams
     */
    defaultBranch?: string;
    /**
     * The new value of whether an application should be publicly visible
     * @type {boolean}
     * @memberof V0AppUpdateParams
     */
    isPublic?: boolean;
    /**
     * The new repository URL for the application.
     * @type {string}
     * @memberof V0AppUpdateParams
     */
    repositoryUrl?: string;
    /**
     * The new service credential user ID (recommendation: use the UI to set this)
     * @type {number}
     * @memberof V0AppUpdateParams
     */
    servicesCredentialUserId?: number;
    /**
     * The new title of the application.
     * @type {string}
     * @memberof V0AppUpdateParams
     */
    title?: string;
}

/**
 * Check if a given object implements the V0AppUpdateParams interface.
 */
export function instanceOfV0AppUpdateParams(value: object): value is V0AppUpdateParams {
    return true;
}

export function V0AppUpdateParamsFromJSON(json: any): V0AppUpdateParams {
    return V0AppUpdateParamsFromJSONTyped(json, false);
}

export function V0AppUpdateParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0AppUpdateParams {
    if (json == null) {
        return json;
    }
    return {
        
        'appleCredentialUserId': json['apple_credential_user_id'] == null ? undefined : json['apple_credential_user_id'],
        'appleCredentialUserSlug': json['apple_credential_user_slug'] == null ? undefined : json['apple_credential_user_slug'],
        'defaultBranch': json['default_branch'] == null ? undefined : json['default_branch'],
        'isPublic': json['is_public'] == null ? undefined : json['is_public'],
        'repositoryUrl': json['repository_url'] == null ? undefined : json['repository_url'],
        'servicesCredentialUserId': json['services_credential_user_id'] == null ? undefined : json['services_credential_user_id'],
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function V0AppUpdateParamsToJSON(json: any): V0AppUpdateParams {
    return V0AppUpdateParamsToJSONTyped(json, false);
}

export function V0AppUpdateParamsToJSONTyped(value?: V0AppUpdateParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'apple_credential_user_id': value['appleCredentialUserId'],
        'apple_credential_user_slug': value['appleCredentialUserSlug'],
        'default_branch': value['defaultBranch'],
        'is_public': value['isPublic'],
        'repository_url': value['repositoryUrl'],
        'services_credential_user_id': value['servicesCredentialUserId'],
        'title': value['title'],
    };
}

