/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V0AppConfigRequestParam
 */
export interface V0AppConfigRequestParam {
    /**
     * The bitrise.yml of your application, defined in JSON format
     * @type {object}
     * @memberof V0AppConfigRequestParam
     */
    appConfigDatastoreYaml: object;
}

/**
 * Check if a given object implements the V0AppConfigRequestParam interface.
 */
export function instanceOfV0AppConfigRequestParam(value: object): value is V0AppConfigRequestParam {
    if (!('appConfigDatastoreYaml' in value) || value['appConfigDatastoreYaml'] === undefined) return false;
    return true;
}

export function V0AppConfigRequestParamFromJSON(json: any): V0AppConfigRequestParam {
    return V0AppConfigRequestParamFromJSONTyped(json, false);
}

export function V0AppConfigRequestParamFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0AppConfigRequestParam {
    if (json == null) {
        return json;
    }
    return {
        
        'appConfigDatastoreYaml': json['app_config_datastore_yaml'],
    };
}

export function V0AppConfigRequestParamToJSON(json: any): V0AppConfigRequestParam {
    return V0AppConfigRequestParamToJSONTyped(json, false);
}

export function V0AppConfigRequestParamToJSONTyped(value?: V0AppConfigRequestParam | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app_config_datastore_yaml': value['appConfigDatastoreYaml'],
    };
}

