/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V0AppAddOnResponseItemModel } from './V0AppAddOnResponseItemModel';
import {
    V0AppAddOnResponseItemModelFromJSON,
    V0AppAddOnResponseItemModelFromJSONTyped,
    V0AppAddOnResponseItemModelToJSON,
    V0AppAddOnResponseItemModelToJSONTyped,
} from './V0AppAddOnResponseItemModel';

/**
 * 
 * @export
 * @interface V0AppAddOnsListResponseModel
 */
export interface V0AppAddOnsListResponseModel {
    /**
     * 
     * @type {Array<V0AppAddOnResponseItemModel>}
     * @memberof V0AppAddOnsListResponseModel
     */
    data?: Array<V0AppAddOnResponseItemModel>;
}

/**
 * Check if a given object implements the V0AppAddOnsListResponseModel interface.
 */
export function instanceOfV0AppAddOnsListResponseModel(value: object): value is V0AppAddOnsListResponseModel {
    return true;
}

export function V0AppAddOnsListResponseModelFromJSON(json: any): V0AppAddOnsListResponseModel {
    return V0AppAddOnsListResponseModelFromJSONTyped(json, false);
}

export function V0AppAddOnsListResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0AppAddOnsListResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(V0AppAddOnResponseItemModelFromJSON)),
    };
}

export function V0AppAddOnsListResponseModelToJSON(json: any): V0AppAddOnsListResponseModel {
    return V0AppAddOnsListResponseModelToJSONTyped(json, false);
}

export function V0AppAddOnsListResponseModelToJSONTyped(value?: V0AppAddOnsListResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(V0AppAddOnResponseItemModelToJSON)),
    };
}

