/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V0AppFinishRespModel
 */
export interface V0AppFinishRespModel {
    /**
     * 
     * @type {string}
     * @memberof V0AppFinishRespModel
     */
    branchName?: string;
    /**
     * 
     * @type {string}
     * @memberof V0AppFinishRespModel
     */
    buildTriggerToken?: string;
    /**
     * 
     * @type {boolean}
     * @memberof V0AppFinishRespModel
     */
    isWebhookAutoRegSupported?: boolean;
    /**
     * 
     * @type {string}
     * @memberof V0AppFinishRespModel
     */
    status?: string;
}

/**
 * Check if a given object implements the V0AppFinishRespModel interface.
 */
export function instanceOfV0AppFinishRespModel(value: object): value is V0AppFinishRespModel {
    return true;
}

export function V0AppFinishRespModelFromJSON(json: any): V0AppFinishRespModel {
    return V0AppFinishRespModelFromJSONTyped(json, false);
}

export function V0AppFinishRespModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0AppFinishRespModel {
    if (json == null) {
        return json;
    }
    return {
        
        'branchName': json['branch_name'] == null ? undefined : json['branch_name'],
        'buildTriggerToken': json['build_trigger_token'] == null ? undefined : json['build_trigger_token'],
        'isWebhookAutoRegSupported': json['is_webhook_auto_reg_supported'] == null ? undefined : json['is_webhook_auto_reg_supported'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function V0AppFinishRespModelToJSON(json: any): V0AppFinishRespModel {
    return V0AppFinishRespModelToJSONTyped(json, false);
}

export function V0AppFinishRespModelToJSONTyped(value?: V0AppFinishRespModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'branch_name': value['branchName'],
        'build_trigger_token': value['buildTriggerToken'],
        'is_webhook_auto_reg_supported': value['isWebhookAutoRegSupported'],
        'status': value['status'],
    };
}

