/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V0AppNotificationSettingsParams
 */
export interface V0AppNotificationSettingsParams {
    /**
     * When should Bitrise send notifications for the users on build failure? Possible values: always, never, change
     * @type {string}
     * @memberof V0AppNotificationSettingsParams
     */
    onFailure?: string;
    /**
     * When should Bitrise send notifications for the users on build success? Possible values: always, never, change
     * @type {string}
     * @memberof V0AppNotificationSettingsParams
     */
    onSuccess?: string;
}

/**
 * Check if a given object implements the V0AppNotificationSettingsParams interface.
 */
export function instanceOfV0AppNotificationSettingsParams(value: object): value is V0AppNotificationSettingsParams {
    return true;
}

export function V0AppNotificationSettingsParamsFromJSON(json: any): V0AppNotificationSettingsParams {
    return V0AppNotificationSettingsParamsFromJSONTyped(json, false);
}

export function V0AppNotificationSettingsParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0AppNotificationSettingsParams {
    if (json == null) {
        return json;
    }
    return {
        
        'onFailure': json['on_failure'] == null ? undefined : json['on_failure'],
        'onSuccess': json['on_success'] == null ? undefined : json['on_success'],
    };
}

export function V0AppNotificationSettingsParamsToJSON(json: any): V0AppNotificationSettingsParams {
    return V0AppNotificationSettingsParamsToJSONTyped(json, false);
}

export function V0AppNotificationSettingsParamsToJSONTyped(value?: V0AppNotificationSettingsParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'on_failure': value['onFailure'],
        'on_success': value['onSuccess'],
    };
}

