/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V0AppWebhookCreateParams
 */
export interface V0AppWebhookCreateParams {
    /**
     * 
     * @type {Array<string>}
     * @memberof V0AppWebhookCreateParams
     */
    events: Array<string>;
    /**
     * 
     * @type {object}
     * @memberof V0AppWebhookCreateParams
     */
    headers?: object;
    /**
     * 
     * @type {string}
     * @memberof V0AppWebhookCreateParams
     */
    secret: string;
    /**
     * 
     * @type {string}
     * @memberof V0AppWebhookCreateParams
     */
    url: string;
}

/**
 * Check if a given object implements the V0AppWebhookCreateParams interface.
 */
export function instanceOfV0AppWebhookCreateParams(value: object): value is V0AppWebhookCreateParams {
    if (!('events' in value) || value['events'] === undefined) return false;
    if (!('secret' in value) || value['secret'] === undefined) return false;
    if (!('url' in value) || value['url'] === undefined) return false;
    return true;
}

export function V0AppWebhookCreateParamsFromJSON(json: any): V0AppWebhookCreateParams {
    return V0AppWebhookCreateParamsFromJSONTyped(json, false);
}

export function V0AppWebhookCreateParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0AppWebhookCreateParams {
    if (json == null) {
        return json;
    }
    return {
        
        'events': json['events'],
        'headers': json['headers'] == null ? undefined : json['headers'],
        'secret': json['secret'],
        'url': json['url'],
    };
}

export function V0AppWebhookCreateParamsToJSON(json: any): V0AppWebhookCreateParams {
    return V0AppWebhookCreateParamsToJSONTyped(json, false);
}

export function V0AppWebhookCreateParamsToJSONTyped(value?: V0AppWebhookCreateParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'events': value['events'],
        'headers': value['headers'],
        'secret': value['secret'],
        'url': value['url'],
    };
}

