/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V0ArchivedBuildArtifact } from './V0ArchivedBuildArtifact';
import {
    V0ArchivedBuildArtifactFromJSON,
    V0ArchivedBuildArtifactFromJSONTyped,
    V0ArchivedBuildArtifactToJSON,
    V0ArchivedBuildArtifactToJSONTyped,
} from './V0ArchivedBuildArtifact';

/**
 * 
 * @export
 * @interface V0ArchivedBuildResponseItemModel
 */
export interface V0ArchivedBuildResponseItemModel {
    /**
     * 
     * @type {string}
     * @memberof V0ArchivedBuildResponseItemModel
     */
    abortReason?: string;
    /**
     * 
     * @type {string}
     * @memberof V0ArchivedBuildResponseItemModel
     */
    branch?: string;
    /**
     * 
     * @type {Array<V0ArchivedBuildArtifact>}
     * @memberof V0ArchivedBuildResponseItemModel
     */
    buildArtifacts?: Array<V0ArchivedBuildArtifact>;
    /**
     * 
     * @type {number}
     * @memberof V0ArchivedBuildResponseItemModel
     */
    buildNumber?: number;
    /**
     * 
     * @type {string}
     * @memberof V0ArchivedBuildResponseItemModel
     */
    commitHash?: string;
    /**
     * 
     * @type {string}
     * @memberof V0ArchivedBuildResponseItemModel
     */
    commitMessage?: string;
    /**
     * 
     * @type {number}
     * @memberof V0ArchivedBuildResponseItemModel
     */
    creditCost?: number;
    /**
     * 
     * @type {string}
     * @memberof V0ArchivedBuildResponseItemModel
     */
    finishedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof V0ArchivedBuildResponseItemModel
     */
    machineTypeId?: string;
    /**
     * 
     * @type {object}
     * @memberof V0ArchivedBuildResponseItemModel
     */
    originalBuildParams?: object;
    /**
     * 
     * @type {string}
     * @memberof V0ArchivedBuildResponseItemModel
     */
    pipelineWorkflowId?: string;
    /**
     * 
     * @type {number}
     * @memberof V0ArchivedBuildResponseItemModel
     */
    pullRequestId?: number;
    /**
     * 
     * @type {string}
     * @memberof V0ArchivedBuildResponseItemModel
     */
    pullRequestTargetBranch?: string;
    /**
     * 
     * @type {string}
     * @memberof V0ArchivedBuildResponseItemModel
     */
    pullRequestViewUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof V0ArchivedBuildResponseItemModel
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof V0ArchivedBuildResponseItemModel
     */
    stackIdentifier?: string;
    /**
     * 
     * @type {string}
     * @memberof V0ArchivedBuildResponseItemModel
     */
    startedOnWorkerAt?: string;
    /**
     * 
     * @type {number}
     * @memberof V0ArchivedBuildResponseItemModel
     */
    status?: number;
    /**
     * 
     * @type {string}
     * @memberof V0ArchivedBuildResponseItemModel
     */
    statusText?: string;
    /**
     * 
     * @type {string}
     * @memberof V0ArchivedBuildResponseItemModel
     */
    tag?: string;
    /**
     * 
     * @type {string}
     * @memberof V0ArchivedBuildResponseItemModel
     */
    triggeredBy?: string;
    /**
     * 
     * @type {string}
     * @memberof V0ArchivedBuildResponseItemModel
     */
    triggeredWorkflow?: string;
}

/**
 * Check if a given object implements the V0ArchivedBuildResponseItemModel interface.
 */
export function instanceOfV0ArchivedBuildResponseItemModel(value: object): value is V0ArchivedBuildResponseItemModel {
    return true;
}

export function V0ArchivedBuildResponseItemModelFromJSON(json: any): V0ArchivedBuildResponseItemModel {
    return V0ArchivedBuildResponseItemModelFromJSONTyped(json, false);
}

export function V0ArchivedBuildResponseItemModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0ArchivedBuildResponseItemModel {
    if (json == null) {
        return json;
    }
    return {
        
        'abortReason': json['abort_reason'] == null ? undefined : json['abort_reason'],
        'branch': json['branch'] == null ? undefined : json['branch'],
        'buildArtifacts': json['build_artifacts'] == null ? undefined : ((json['build_artifacts'] as Array<any>).map(V0ArchivedBuildArtifactFromJSON)),
        'buildNumber': json['build_number'] == null ? undefined : json['build_number'],
        'commitHash': json['commit_hash'] == null ? undefined : json['commit_hash'],
        'commitMessage': json['commit_message'] == null ? undefined : json['commit_message'],
        'creditCost': json['credit_cost'] == null ? undefined : json['credit_cost'],
        'finishedAt': json['finished_at'] == null ? undefined : json['finished_at'],
        'machineTypeId': json['machine_type_id'] == null ? undefined : json['machine_type_id'],
        'originalBuildParams': json['original_build_params'] == null ? undefined : json['original_build_params'],
        'pipelineWorkflowId': json['pipeline_workflow_id'] == null ? undefined : json['pipeline_workflow_id'],
        'pullRequestId': json['pull_request_id'] == null ? undefined : json['pull_request_id'],
        'pullRequestTargetBranch': json['pull_request_target_branch'] == null ? undefined : json['pull_request_target_branch'],
        'pullRequestViewUrl': json['pull_request_view_url'] == null ? undefined : json['pull_request_view_url'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'stackIdentifier': json['stack_identifier'] == null ? undefined : json['stack_identifier'],
        'startedOnWorkerAt': json['started_on_worker_at'] == null ? undefined : json['started_on_worker_at'],
        'status': json['status'] == null ? undefined : json['status'],
        'statusText': json['status_text'] == null ? undefined : json['status_text'],
        'tag': json['tag'] == null ? undefined : json['tag'],
        'triggeredBy': json['triggered_by'] == null ? undefined : json['triggered_by'],
        'triggeredWorkflow': json['triggered_workflow'] == null ? undefined : json['triggered_workflow'],
    };
}

export function V0ArchivedBuildResponseItemModelToJSON(json: any): V0ArchivedBuildResponseItemModel {
    return V0ArchivedBuildResponseItemModelToJSONTyped(json, false);
}

export function V0ArchivedBuildResponseItemModelToJSONTyped(value?: V0ArchivedBuildResponseItemModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'abort_reason': value['abortReason'],
        'branch': value['branch'],
        'build_artifacts': value['buildArtifacts'] == null ? undefined : ((value['buildArtifacts'] as Array<any>).map(V0ArchivedBuildArtifactToJSON)),
        'build_number': value['buildNumber'],
        'commit_hash': value['commitHash'],
        'commit_message': value['commitMessage'],
        'credit_cost': value['creditCost'],
        'finished_at': value['finishedAt'],
        'machine_type_id': value['machineTypeId'],
        'original_build_params': value['originalBuildParams'],
        'pipeline_workflow_id': value['pipelineWorkflowId'],
        'pull_request_id': value['pullRequestId'],
        'pull_request_target_branch': value['pullRequestTargetBranch'],
        'pull_request_view_url': value['pullRequestViewUrl'],
        'slug': value['slug'],
        'stack_identifier': value['stackIdentifier'],
        'started_on_worker_at': value['startedOnWorkerAt'],
        'status': value['status'],
        'status_text': value['statusText'],
        'tag': value['tag'],
        'triggered_by': value['triggeredBy'],
        'triggered_workflow': value['triggeredWorkflow'],
    };
}

