/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V0PagingResponseModel } from './V0PagingResponseModel';
import {
    V0PagingResponseModelFromJSON,
    V0PagingResponseModelFromJSONTyped,
    V0PagingResponseModelToJSON,
    V0PagingResponseModelToJSONTyped,
} from './V0PagingResponseModel';
import type { V0ArchivedBuildResponseItemModel } from './V0ArchivedBuildResponseItemModel';
import {
    V0ArchivedBuildResponseItemModelFromJSON,
    V0ArchivedBuildResponseItemModelFromJSONTyped,
    V0ArchivedBuildResponseItemModelToJSON,
    V0ArchivedBuildResponseItemModelToJSONTyped,
} from './V0ArchivedBuildResponseItemModel';

/**
 * 
 * @export
 * @interface V0ArchivedBuildListResponseModel
 */
export interface V0ArchivedBuildListResponseModel {
    /**
     * 
     * @type {Array<V0ArchivedBuildResponseItemModel>}
     * @memberof V0ArchivedBuildListResponseModel
     */
    data?: Array<V0ArchivedBuildResponseItemModel>;
    /**
     * pagination
     * @type {V0PagingResponseModel}
     * @memberof V0ArchivedBuildListResponseModel
     */
    paging?: V0PagingResponseModel;
}

/**
 * Check if a given object implements the V0ArchivedBuildListResponseModel interface.
 */
export function instanceOfV0ArchivedBuildListResponseModel(value: object): value is V0ArchivedBuildListResponseModel {
    return true;
}

export function V0ArchivedBuildListResponseModelFromJSON(json: any): V0ArchivedBuildListResponseModel {
    return V0ArchivedBuildListResponseModelFromJSONTyped(json, false);
}

export function V0ArchivedBuildListResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0ArchivedBuildListResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(V0ArchivedBuildResponseItemModelFromJSON)),
        'paging': json['paging'] == null ? undefined : V0PagingResponseModelFromJSON(json['paging']),
    };
}

export function V0ArchivedBuildListResponseModelToJSON(json: any): V0ArchivedBuildListResponseModel {
    return V0ArchivedBuildListResponseModelToJSONTyped(json, false);
}

export function V0ArchivedBuildListResponseModelToJSONTyped(value?: V0ArchivedBuildListResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(V0ArchivedBuildResponseItemModelToJSON)),
        'paging': V0PagingResponseModelToJSON(value['paging']),
    };
}

