/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V0BuildCertificateResponseItemModel } from './V0BuildCertificateResponseItemModel';
import {
    V0BuildCertificateResponseItemModelFromJSON,
    V0BuildCertificateResponseItemModelFromJSONTyped,
    V0BuildCertificateResponseItemModelToJSON,
    V0BuildCertificateResponseItemModelToJSONTyped,
} from './V0BuildCertificateResponseItemModel';

/**
 * 
 * @export
 * @interface V0BuildCertificateResponseModel
 */
export interface V0BuildCertificateResponseModel {
    /**
     * 
     * @type {V0BuildCertificateResponseItemModel}
     * @memberof V0BuildCertificateResponseModel
     */
    data?: V0BuildCertificateResponseItemModel;
}

/**
 * Check if a given object implements the V0BuildCertificateResponseModel interface.
 */
export function instanceOfV0BuildCertificateResponseModel(value: object): value is V0BuildCertificateResponseModel {
    return true;
}

export function V0BuildCertificateResponseModelFromJSON(json: any): V0BuildCertificateResponseModel {
    return V0BuildCertificateResponseModelFromJSONTyped(json, false);
}

export function V0BuildCertificateResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0BuildCertificateResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : V0BuildCertificateResponseItemModelFromJSON(json['data']),
    };
}

export function V0BuildCertificateResponseModelToJSON(json: any): V0BuildCertificateResponseModel {
    return V0BuildCertificateResponseModelToJSONTyped(json, false);
}

export function V0BuildCertificateResponseModelToJSONTyped(value?: V0BuildCertificateResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': V0BuildCertificateResponseItemModelToJSON(value['data']),
    };
}

