/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V0BuildTriggerRespItemModel } from './V0BuildTriggerRespItemModel';
import {
    V0BuildTriggerRespItemModelFromJSON,
    V0BuildTriggerRespItemModelFromJSONTyped,
    V0BuildTriggerRespItemModelToJSON,
    V0BuildTriggerRespItemModelToJSONTyped,
} from './V0BuildTriggerRespItemModel';

/**
 * 
 * @export
 * @interface V0BuildTriggerRespModel
 */
export interface V0BuildTriggerRespModel {
    /**
     * Deprecated
     * @type {number}
     * @memberof V0BuildTriggerRespModel
     */
    buildNumber?: number;
    /**
     * Deprecated
     * @type {string}
     * @memberof V0BuildTriggerRespModel
     */
    buildSlug?: string;
    /**
     * Deprecated
     * @type {string}
     * @memberof V0BuildTriggerRespModel
     */
    buildUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof V0BuildTriggerRespModel
     */
    message?: string;
    /**
     * 
     * @type {Array<V0BuildTriggerRespItemModel>}
     * @memberof V0BuildTriggerRespModel
     */
    results?: Array<V0BuildTriggerRespItemModel>;
    /**
     * 
     * @type {string}
     * @memberof V0BuildTriggerRespModel
     */
    service?: string;
    /**
     * 
     * @type {string}
     * @memberof V0BuildTriggerRespModel
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof V0BuildTriggerRespModel
     */
    status?: string;
    /**
     * Deprecated
     * @type {string}
     * @memberof V0BuildTriggerRespModel
     */
    triggeredWorkflow?: string;
}

/**
 * Check if a given object implements the V0BuildTriggerRespModel interface.
 */
export function instanceOfV0BuildTriggerRespModel(value: object): value is V0BuildTriggerRespModel {
    return true;
}

export function V0BuildTriggerRespModelFromJSON(json: any): V0BuildTriggerRespModel {
    return V0BuildTriggerRespModelFromJSONTyped(json, false);
}

export function V0BuildTriggerRespModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0BuildTriggerRespModel {
    if (json == null) {
        return json;
    }
    return {
        
        'buildNumber': json['build_number'] == null ? undefined : json['build_number'],
        'buildSlug': json['build_slug'] == null ? undefined : json['build_slug'],
        'buildUrl': json['build_url'] == null ? undefined : json['build_url'],
        'message': json['message'] == null ? undefined : json['message'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(V0BuildTriggerRespItemModelFromJSON)),
        'service': json['service'] == null ? undefined : json['service'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'status': json['status'] == null ? undefined : json['status'],
        'triggeredWorkflow': json['triggered_workflow'] == null ? undefined : json['triggered_workflow'],
    };
}

export function V0BuildTriggerRespModelToJSON(json: any): V0BuildTriggerRespModel {
    return V0BuildTriggerRespModelToJSONTyped(json, false);
}

export function V0BuildTriggerRespModelToJSONTyped(value?: V0BuildTriggerRespModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'build_number': value['buildNumber'],
        'build_slug': value['buildSlug'],
        'build_url': value['buildUrl'],
        'message': value['message'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(V0BuildTriggerRespItemModelToJSON)),
        'service': value['service'],
        'slug': value['slug'],
        'status': value['status'],
        'triggered_workflow': value['triggeredWorkflow'],
    };
}

