/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V0BuildTriggerParamsHookInfo
 */
export interface V0BuildTriggerParamsHookInfo {
    /**
     * Should be "bitrise"
     * @type {string}
     * @memberof V0BuildTriggerParamsHookInfo
     */
    type?: string;
}

/**
 * Check if a given object implements the V0BuildTriggerParamsHookInfo interface.
 */
export function instanceOfV0BuildTriggerParamsHookInfo(value: object): value is V0BuildTriggerParamsHookInfo {
    return true;
}

export function V0BuildTriggerParamsHookInfoFromJSON(json: any): V0BuildTriggerParamsHookInfo {
    return V0BuildTriggerParamsHookInfoFromJSONTyped(json, false);
}

export function V0BuildTriggerParamsHookInfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0BuildTriggerParamsHookInfo {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
    };
}

export function V0BuildTriggerParamsHookInfoToJSON(json: any): V0BuildTriggerParamsHookInfo {
    return V0BuildTriggerParamsHookInfoToJSONTyped(json, false);
}

export function V0BuildTriggerParamsHookInfoToJSONTyped(value?: V0BuildTriggerParamsHookInfo | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
    };
}

