/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V0BuildCertificateUploadResponseItemModel } from './V0BuildCertificateUploadResponseItemModel';
import {
    V0BuildCertificateUploadResponseItemModelFromJSON,
    V0BuildCertificateUploadResponseItemModelFromJSONTyped,
    V0BuildCertificateUploadResponseItemModelToJSON,
    V0BuildCertificateUploadResponseItemModelToJSONTyped,
} from './V0BuildCertificateUploadResponseItemModel';

/**
 * 
 * @export
 * @interface V0BuildCertificateUploadResponseModel
 */
export interface V0BuildCertificateUploadResponseModel {
    /**
     * 
     * @type {V0BuildCertificateUploadResponseItemModel}
     * @memberof V0BuildCertificateUploadResponseModel
     */
    data?: V0BuildCertificateUploadResponseItemModel;
}

/**
 * Check if a given object implements the V0BuildCertificateUploadResponseModel interface.
 */
export function instanceOfV0BuildCertificateUploadResponseModel(value: object): value is V0BuildCertificateUploadResponseModel {
    return true;
}

export function V0BuildCertificateUploadResponseModelFromJSON(json: any): V0BuildCertificateUploadResponseModel {
    return V0BuildCertificateUploadResponseModelFromJSONTyped(json, false);
}

export function V0BuildCertificateUploadResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0BuildCertificateUploadResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : V0BuildCertificateUploadResponseItemModelFromJSON(json['data']),
    };
}

export function V0BuildCertificateUploadResponseModelToJSON(json: any): V0BuildCertificateUploadResponseModel {
    return V0BuildCertificateUploadResponseModelToJSONTyped(json, false);
}

export function V0BuildCertificateUploadResponseModelToJSONTyped(value?: V0BuildCertificateUploadResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': V0BuildCertificateUploadResponseItemModelToJSON(value['data']),
    };
}

