/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V0PagingResponseModel } from './V0PagingResponseModel';
import {
    V0PagingResponseModelFromJSON,
    V0PagingResponseModelFromJSONTyped,
    V0PagingResponseModelToJSON,
    V0PagingResponseModelToJSONTyped,
} from './V0PagingResponseModel';
import type { V0BuildListAllResponseItemModel } from './V0BuildListAllResponseItemModel';
import {
    V0BuildListAllResponseItemModelFromJSON,
    V0BuildListAllResponseItemModelFromJSONTyped,
    V0BuildListAllResponseItemModelToJSON,
    V0BuildListAllResponseItemModelToJSONTyped,
} from './V0BuildListAllResponseItemModel';

/**
 * 
 * @export
 * @interface V0BuildListAllResponseModel
 */
export interface V0BuildListAllResponseModel {
    /**
     * 
     * @type {Array<V0BuildListAllResponseItemModel>}
     * @memberof V0BuildListAllResponseModel
     */
    data?: Array<V0BuildListAllResponseItemModel>;
    /**
     * pagination
     * @type {V0PagingResponseModel}
     * @memberof V0BuildListAllResponseModel
     */
    paging?: V0PagingResponseModel;
}

/**
 * Check if a given object implements the V0BuildListAllResponseModel interface.
 */
export function instanceOfV0BuildListAllResponseModel(value: object): value is V0BuildListAllResponseModel {
    return true;
}

export function V0BuildListAllResponseModelFromJSON(json: any): V0BuildListAllResponseModel {
    return V0BuildListAllResponseModelFromJSONTyped(json, false);
}

export function V0BuildListAllResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0BuildListAllResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(V0BuildListAllResponseItemModelFromJSON)),
        'paging': json['paging'] == null ? undefined : V0PagingResponseModelFromJSON(json['paging']),
    };
}

export function V0BuildListAllResponseModelToJSON(json: any): V0BuildListAllResponseModel {
    return V0BuildListAllResponseModelToJSONTyped(json, false);
}

export function V0BuildListAllResponseModelToJSONTyped(value?: V0BuildListAllResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(V0BuildListAllResponseItemModelToJSON)),
        'paging': V0PagingResponseModelToJSON(value['paging']),
    };
}

