/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V0BuildRequestUpdateParams
 */
export interface V0BuildRequestUpdateParams {
    /**
     * 
     * @type {boolean}
     * @memberof V0BuildRequestUpdateParams
     */
    isApproved: boolean;
}

/**
 * Check if a given object implements the V0BuildRequestUpdateParams interface.
 */
export function instanceOfV0BuildRequestUpdateParams(value: object): value is V0BuildRequestUpdateParams {
    if (!('isApproved' in value) || value['isApproved'] === undefined) return false;
    return true;
}

export function V0BuildRequestUpdateParamsFromJSON(json: any): V0BuildRequestUpdateParams {
    return V0BuildRequestUpdateParamsFromJSONTyped(json, false);
}

export function V0BuildRequestUpdateParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0BuildRequestUpdateParams {
    if (json == null) {
        return json;
    }
    return {
        
        'isApproved': json['is_approved'],
    };
}

export function V0BuildRequestUpdateParamsToJSON(json: any): V0BuildRequestUpdateParams {
    return V0BuildRequestUpdateParamsToJSONTyped(json, false);
}

export function V0BuildRequestUpdateParamsToJSONTyped(value?: V0BuildRequestUpdateParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'is_approved': value['isApproved'],
    };
}

