/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V0BuildWorkflowListResponseModel
 */
export interface V0BuildWorkflowListResponseModel {
    /**
     * 
     * @type {Array<string>}
     * @memberof V0BuildWorkflowListResponseModel
     */
    data?: Array<string>;
}

/**
 * Check if a given object implements the V0BuildWorkflowListResponseModel interface.
 */
export function instanceOfV0BuildWorkflowListResponseModel(value: object): value is V0BuildWorkflowListResponseModel {
    return true;
}

export function V0BuildWorkflowListResponseModelFromJSON(json: any): V0BuildWorkflowListResponseModel {
    return V0BuildWorkflowListResponseModelFromJSONTyped(json, false);
}

export function V0BuildWorkflowListResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0BuildWorkflowListResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : json['data'],
    };
}

export function V0BuildWorkflowListResponseModelToJSON(json: any): V0BuildWorkflowListResponseModel {
    return V0BuildWorkflowListResponseModelToJSONTyped(json, false);
}

export function V0BuildWorkflowListResponseModelToJSONTyped(value?: V0BuildWorkflowListResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
    };
}

