/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V0PagingResponseModel } from './V0PagingResponseModel';
import {
    V0PagingResponseModelFromJSON,
    V0PagingResponseModelFromJSONTyped,
    V0PagingResponseModelToJSON,
    V0PagingResponseModelToJSONTyped,
} from './V0PagingResponseModel';
import type { V0BuildCertificateResponseItemModel } from './V0BuildCertificateResponseItemModel';
import {
    V0BuildCertificateResponseItemModelFromJSON,
    V0BuildCertificateResponseItemModelFromJSONTyped,
    V0BuildCertificateResponseItemModelToJSON,
    V0BuildCertificateResponseItemModelToJSONTyped,
} from './V0BuildCertificateResponseItemModel';

/**
 * 
 * @export
 * @interface V0BuildCertificateListResponseModel
 */
export interface V0BuildCertificateListResponseModel {
    /**
     * 
     * @type {Array<V0BuildCertificateResponseItemModel>}
     * @memberof V0BuildCertificateListResponseModel
     */
    data?: Array<V0BuildCertificateResponseItemModel>;
    /**
     * pagination
     * @type {V0PagingResponseModel}
     * @memberof V0BuildCertificateListResponseModel
     */
    paging?: V0PagingResponseModel;
}

/**
 * Check if a given object implements the V0BuildCertificateListResponseModel interface.
 */
export function instanceOfV0BuildCertificateListResponseModel(value: object): value is V0BuildCertificateListResponseModel {
    return true;
}

export function V0BuildCertificateListResponseModelFromJSON(json: any): V0BuildCertificateListResponseModel {
    return V0BuildCertificateListResponseModelFromJSONTyped(json, false);
}

export function V0BuildCertificateListResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0BuildCertificateListResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(V0BuildCertificateResponseItemModelFromJSON)),
        'paging': json['paging'] == null ? undefined : V0PagingResponseModelFromJSON(json['paging']),
    };
}

export function V0BuildCertificateListResponseModelToJSON(json: any): V0BuildCertificateListResponseModel {
    return V0BuildCertificateListResponseModelToJSONTyped(json, false);
}

export function V0BuildCertificateListResponseModelToJSONTyped(value?: V0BuildCertificateListResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(V0BuildCertificateResponseItemModelToJSON)),
        'paging': V0PagingResponseModelToJSON(value['paging']),
    };
}

