/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V0BuildCertificateDownloadResponseItemModel
 */
export interface V0BuildCertificateDownloadResponseItemModel {
    /**
     * 
     * @type {string}
     * @memberof V0BuildCertificateDownloadResponseItemModel
     */
    certificatePassword?: string;
    /**
     * 
     * @type {string}
     * @memberof V0BuildCertificateDownloadResponseItemModel
     */
    downloadUrl?: string;
    /**
     * 
     * @type {boolean}
     * @memberof V0BuildCertificateDownloadResponseItemModel
     */
    isExpose?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof V0BuildCertificateDownloadResponseItemModel
     */
    isProtected?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof V0BuildCertificateDownloadResponseItemModel
     */
    processed?: boolean;
    /**
     * 
     * @type {string}
     * @memberof V0BuildCertificateDownloadResponseItemModel
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof V0BuildCertificateDownloadResponseItemModel
     */
    uploadFileName?: string;
    /**
     * 
     * @type {number}
     * @memberof V0BuildCertificateDownloadResponseItemModel
     */
    uploadFileSize?: number;
}

/**
 * Check if a given object implements the V0BuildCertificateDownloadResponseItemModel interface.
 */
export function instanceOfV0BuildCertificateDownloadResponseItemModel(value: object): value is V0BuildCertificateDownloadResponseItemModel {
    return true;
}

export function V0BuildCertificateDownloadResponseItemModelFromJSON(json: any): V0BuildCertificateDownloadResponseItemModel {
    return V0BuildCertificateDownloadResponseItemModelFromJSONTyped(json, false);
}

export function V0BuildCertificateDownloadResponseItemModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0BuildCertificateDownloadResponseItemModel {
    if (json == null) {
        return json;
    }
    return {
        
        'certificatePassword': json['certificate_password'] == null ? undefined : json['certificate_password'],
        'downloadUrl': json['download_url'] == null ? undefined : json['download_url'],
        'isExpose': json['is_expose'] == null ? undefined : json['is_expose'],
        'isProtected': json['is_protected'] == null ? undefined : json['is_protected'],
        'processed': json['processed'] == null ? undefined : json['processed'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'uploadFileName': json['upload_file_name'] == null ? undefined : json['upload_file_name'],
        'uploadFileSize': json['upload_file_size'] == null ? undefined : json['upload_file_size'],
    };
}

export function V0BuildCertificateDownloadResponseItemModelToJSON(json: any): V0BuildCertificateDownloadResponseItemModel {
    return V0BuildCertificateDownloadResponseItemModelToJSONTyped(json, false);
}

export function V0BuildCertificateDownloadResponseItemModelToJSONTyped(value?: V0BuildCertificateDownloadResponseItemModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'certificate_password': value['certificatePassword'],
        'download_url': value['downloadUrl'],
        'is_expose': value['isExpose'],
        'is_protected': value['isProtected'],
        'processed': value['processed'],
        'slug': value['slug'],
        'upload_file_name': value['uploadFileName'],
        'upload_file_size': value['uploadFileSize'],
    };
}

