/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V0CacheItemDownloadURLResponseModel
 */
export interface V0CacheItemDownloadURLResponseModel {
    /**
     * 
     * @type {string}
     * @memberof V0CacheItemDownloadURLResponseModel
     */
    downloadUrl?: string;
}

/**
 * Check if a given object implements the V0CacheItemDownloadURLResponseModel interface.
 */
export function instanceOfV0CacheItemDownloadURLResponseModel(value: object): value is V0CacheItemDownloadURLResponseModel {
    return true;
}

export function V0CacheItemDownloadURLResponseModelFromJSON(json: any): V0CacheItemDownloadURLResponseModel {
    return V0CacheItemDownloadURLResponseModelFromJSONTyped(json, false);
}

export function V0CacheItemDownloadURLResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0CacheItemDownloadURLResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'downloadUrl': json['download_url'] == null ? undefined : json['download_url'],
    };
}

export function V0CacheItemDownloadURLResponseModelToJSON(json: any): V0CacheItemDownloadURLResponseModel {
    return V0CacheItemDownloadURLResponseModelToJSONTyped(json, false);
}

export function V0CacheItemDownloadURLResponseModelToJSONTyped(value?: V0CacheItemDownloadURLResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'download_url': value['downloadUrl'],
    };
}

