/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V0CacheItemDownloadURLResponseModel } from './V0CacheItemDownloadURLResponseModel';
import {
    V0CacheItemDownloadURLResponseModelFromJSON,
    V0CacheItemDownloadURLResponseModelFromJSONTyped,
    V0CacheItemDownloadURLResponseModelToJSON,
    V0CacheItemDownloadURLResponseModelToJSONTyped,
} from './V0CacheItemDownloadURLResponseModel';

/**
 * 
 * @export
 * @interface V0CacheItemDownloadResponseModel
 */
export interface V0CacheItemDownloadResponseModel {
    /**
     * 
     * @type {V0CacheItemDownloadURLResponseModel}
     * @memberof V0CacheItemDownloadResponseModel
     */
    data?: V0CacheItemDownloadURLResponseModel;
}

/**
 * Check if a given object implements the V0CacheItemDownloadResponseModel interface.
 */
export function instanceOfV0CacheItemDownloadResponseModel(value: object): value is V0CacheItemDownloadResponseModel {
    return true;
}

export function V0CacheItemDownloadResponseModelFromJSON(json: any): V0CacheItemDownloadResponseModel {
    return V0CacheItemDownloadResponseModelFromJSONTyped(json, false);
}

export function V0CacheItemDownloadResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0CacheItemDownloadResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : V0CacheItemDownloadURLResponseModelFromJSON(json['data']),
    };
}

export function V0CacheItemDownloadResponseModelToJSON(json: any): V0CacheItemDownloadResponseModel {
    return V0CacheItemDownloadResponseModelToJSONTyped(json, false);
}

export function V0CacheItemDownloadResponseModelToJSONTyped(value?: V0CacheItemDownloadResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': V0CacheItemDownloadURLResponseModelToJSON(value['data']),
    };
}

