/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V0CacheItemListResponseItemModel
 */
export interface V0CacheItemListResponseItemModel {
    /**
     * 
     * @type {string}
     * @memberof V0CacheItemListResponseItemModel
     */
    appId?: string;
    /**
     * 
     * @type {string}
     * @memberof V0CacheItemListResponseItemModel
     */
    archiveFilename?: string;
    /**
     * 
     * @type {number}
     * @memberof V0CacheItemListResponseItemModel
     */
    archiveSize?: number;
    /**
     * 
     * @type {string}
     * @memberof V0CacheItemListResponseItemModel
     */
    cacheKey?: string;
    /**
     * 
     * @type {string}
     * @memberof V0CacheItemListResponseItemModel
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof V0CacheItemListResponseItemModel
     */
    expiresAt?: string;
    /**
     * 
     * @type {string}
     * @memberof V0CacheItemListResponseItemModel
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof V0CacheItemListResponseItemModel
     */
    lastUsedAt?: string;
}

/**
 * Check if a given object implements the V0CacheItemListResponseItemModel interface.
 */
export function instanceOfV0CacheItemListResponseItemModel(value: object): value is V0CacheItemListResponseItemModel {
    return true;
}

export function V0CacheItemListResponseItemModelFromJSON(json: any): V0CacheItemListResponseItemModel {
    return V0CacheItemListResponseItemModelFromJSONTyped(json, false);
}

export function V0CacheItemListResponseItemModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0CacheItemListResponseItemModel {
    if (json == null) {
        return json;
    }
    return {
        
        'appId': json['app_id'] == null ? undefined : json['app_id'],
        'archiveFilename': json['archive_filename'] == null ? undefined : json['archive_filename'],
        'archiveSize': json['archive_size'] == null ? undefined : json['archive_size'],
        'cacheKey': json['cache_key'] == null ? undefined : json['cache_key'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'expiresAt': json['expires_at'] == null ? undefined : json['expires_at'],
        'id': json['id'] == null ? undefined : json['id'],
        'lastUsedAt': json['last_used_at'] == null ? undefined : json['last_used_at'],
    };
}

export function V0CacheItemListResponseItemModelToJSON(json: any): V0CacheItemListResponseItemModel {
    return V0CacheItemListResponseItemModelToJSONTyped(json, false);
}

export function V0CacheItemListResponseItemModelToJSONTyped(value?: V0CacheItemListResponseItemModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'app_id': value['appId'],
        'archive_filename': value['archiveFilename'],
        'archive_size': value['archiveSize'],
        'cache_key': value['cacheKey'],
        'created_at': value['createdAt'],
        'expires_at': value['expiresAt'],
        'id': value['id'],
        'last_used_at': value['lastUsedAt'],
    };
}

