/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V0PagingResponseModel } from './V0PagingResponseModel';
import {
    V0PagingResponseModelFromJSON,
    V0PagingResponseModelFromJSONTyped,
    V0PagingResponseModelToJSON,
    V0PagingResponseModelToJSONTyped,
} from './V0PagingResponseModel';
import type { V0CacheItemListResponseItemModel } from './V0CacheItemListResponseItemModel';
import {
    V0CacheItemListResponseItemModelFromJSON,
    V0CacheItemListResponseItemModelFromJSONTyped,
    V0CacheItemListResponseItemModelToJSON,
    V0CacheItemListResponseItemModelToJSONTyped,
} from './V0CacheItemListResponseItemModel';

/**
 * 
 * @export
 * @interface V0CacheItemListResponseModel
 */
export interface V0CacheItemListResponseModel {
    /**
     * 
     * @type {Array<V0CacheItemListResponseItemModel>}
     * @memberof V0CacheItemListResponseModel
     */
    data?: Array<V0CacheItemListResponseItemModel>;
    /**
     * 
     * @type {V0PagingResponseModel}
     * @memberof V0CacheItemListResponseModel
     */
    paging?: V0PagingResponseModel;
}

/**
 * Check if a given object implements the V0CacheItemListResponseModel interface.
 */
export function instanceOfV0CacheItemListResponseModel(value: object): value is V0CacheItemListResponseModel {
    return true;
}

export function V0CacheItemListResponseModelFromJSON(json: any): V0CacheItemListResponseModel {
    return V0CacheItemListResponseModelFromJSONTyped(json, false);
}

export function V0CacheItemListResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0CacheItemListResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(V0CacheItemListResponseItemModelFromJSON)),
        'paging': json['paging'] == null ? undefined : V0PagingResponseModelFromJSON(json['paging']),
    };
}

export function V0CacheItemListResponseModelToJSON(json: any): V0CacheItemListResponseModel {
    return V0CacheItemListResponseModelToJSONTyped(json, false);
}

export function V0CacheItemListResponseModelToJSONTyped(value?: V0CacheItemListResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(V0CacheItemListResponseItemModelToJSON)),
        'paging': V0PagingResponseModelToJSON(value['paging']),
    };
}

