/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V0OrganizationDataModel } from './V0OrganizationDataModel';
import {
    V0OrganizationDataModelFromJSON,
    V0OrganizationDataModelFromJSONTyped,
    V0OrganizationDataModelToJSON,
    V0OrganizationDataModelToJSONTyped,
} from './V0OrganizationDataModel';

/**
 * 
 * @export
 * @interface V0OrganizationListRespModel
 */
export interface V0OrganizationListRespModel {
    /**
     * 
     * @type {Array<V0OrganizationDataModel>}
     * @memberof V0OrganizationListRespModel
     */
    data?: Array<V0OrganizationDataModel>;
}

/**
 * Check if a given object implements the V0OrganizationListRespModel interface.
 */
export function instanceOfV0OrganizationListRespModel(value: object): value is V0OrganizationListRespModel {
    return true;
}

export function V0OrganizationListRespModelFromJSON(json: any): V0OrganizationListRespModel {
    return V0OrganizationListRespModelFromJSONTyped(json, false);
}

export function V0OrganizationListRespModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0OrganizationListRespModel {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(V0OrganizationDataModelFromJSON)),
    };
}

export function V0OrganizationListRespModelToJSON(json: any): V0OrganizationListRespModel {
    return V0OrganizationListRespModelToJSONTyped(json, false);
}

export function V0OrganizationListRespModelToJSONTyped(value?: V0OrganizationListRespModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(V0OrganizationDataModelToJSON)),
    };
}

