/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V0OrganizationGoogleServiceCredetialCreateParams
 */
export interface V0OrganizationGoogleServiceCredetialCreateParams {
    /**
     * 
     * @type {string}
     * @memberof V0OrganizationGoogleServiceCredetialCreateParams
     */
    credentials?: string;
    /**
     * 
     * @type {string}
     * @memberof V0OrganizationGoogleServiceCredetialCreateParams
     */
    name?: string;
}

/**
 * Check if a given object implements the V0OrganizationGoogleServiceCredetialCreateParams interface.
 */
export function instanceOfV0OrganizationGoogleServiceCredetialCreateParams(value: object): value is V0OrganizationGoogleServiceCredetialCreateParams {
    return true;
}

export function V0OrganizationGoogleServiceCredetialCreateParamsFromJSON(json: any): V0OrganizationGoogleServiceCredetialCreateParams {
    return V0OrganizationGoogleServiceCredetialCreateParamsFromJSONTyped(json, false);
}

export function V0OrganizationGoogleServiceCredetialCreateParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0OrganizationGoogleServiceCredetialCreateParams {
    if (json == null) {
        return json;
    }
    return {
        
        'credentials': json['credentials'] == null ? undefined : json['credentials'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function V0OrganizationGoogleServiceCredetialCreateParamsToJSON(json: any): V0OrganizationGoogleServiceCredetialCreateParams {
    return V0OrganizationGoogleServiceCredetialCreateParamsToJSONTyped(json, false);
}

export function V0OrganizationGoogleServiceCredetialCreateParamsToJSONTyped(value?: V0OrganizationGoogleServiceCredetialCreateParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'credentials': value['credentials'],
        'name': value['name'],
    };
}

