/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V0OrganizationUpdateMachineTypeParams
 */
export interface V0OrganizationUpdateMachineTypeParams {
    /**
     * Machine type to migrate from
     * @type {string}
     * @memberof V0OrganizationUpdateMachineTypeParams
     */
    fromMachine?: string;
    /**
     * Machine type to migrate to
     * @type {string}
     * @memberof V0OrganizationUpdateMachineTypeParams
     */
    toMachine?: string;
}

/**
 * Check if a given object implements the V0OrganizationUpdateMachineTypeParams interface.
 */
export function instanceOfV0OrganizationUpdateMachineTypeParams(value: object): value is V0OrganizationUpdateMachineTypeParams {
    return true;
}

export function V0OrganizationUpdateMachineTypeParamsFromJSON(json: any): V0OrganizationUpdateMachineTypeParams {
    return V0OrganizationUpdateMachineTypeParamsFromJSONTyped(json, false);
}

export function V0OrganizationUpdateMachineTypeParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0OrganizationUpdateMachineTypeParams {
    if (json == null) {
        return json;
    }
    return {
        
        'fromMachine': json['from_machine'] == null ? undefined : json['from_machine'],
        'toMachine': json['to_machine'] == null ? undefined : json['to_machine'],
    };
}

export function V0OrganizationUpdateMachineTypeParamsToJSON(json: any): V0OrganizationUpdateMachineTypeParams {
    return V0OrganizationUpdateMachineTypeParamsToJSONTyped(json, false);
}

export function V0OrganizationUpdateMachineTypeParamsToJSONTyped(value?: V0OrganizationUpdateMachineTypeParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'from_machine': value['fromMachine'],
        'to_machine': value['toMachine'],
    };
}

