/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V0OrganizationDataModel } from './V0OrganizationDataModel';
import {
    V0OrganizationDataModelFromJSON,
    V0OrganizationDataModelFromJSONTyped,
    V0OrganizationDataModelToJSON,
    V0OrganizationDataModelToJSONTyped,
} from './V0OrganizationDataModel';

/**
 * 
 * @export
 * @interface V0OrganizationRespModel
 */
export interface V0OrganizationRespModel {
    /**
     * 
     * @type {V0OrganizationDataModel}
     * @memberof V0OrganizationRespModel
     */
    data?: V0OrganizationDataModel;
}

/**
 * Check if a given object implements the V0OrganizationRespModel interface.
 */
export function instanceOfV0OrganizationRespModel(value: object): value is V0OrganizationRespModel {
    return true;
}

export function V0OrganizationRespModelFromJSON(json: any): V0OrganizationRespModel {
    return V0OrganizationRespModelFromJSONTyped(json, false);
}

export function V0OrganizationRespModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0OrganizationRespModel {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : V0OrganizationDataModelFromJSON(json['data']),
    };
}

export function V0OrganizationRespModelToJSON(json: any): V0OrganizationRespModel {
    return V0OrganizationRespModelToJSONTyped(json, false);
}

export function V0OrganizationRespModelToJSONTyped(value?: V0OrganizationRespModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': V0OrganizationDataModelToJSON(value['data']),
    };
}

