/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V0OrganizationAppleAPICredentialResponseItem } from './V0OrganizationAppleAPICredentialResponseItem';
import {
    V0OrganizationAppleAPICredentialResponseItemFromJSON,
    V0OrganizationAppleAPICredentialResponseItemFromJSONTyped,
    V0OrganizationAppleAPICredentialResponseItemToJSON,
    V0OrganizationAppleAPICredentialResponseItemToJSONTyped,
} from './V0OrganizationAppleAPICredentialResponseItem';

/**
 * 
 * @export
 * @interface V0OrganizationAppleAPICredentialsListResponse
 */
export interface V0OrganizationAppleAPICredentialsListResponse {
    /**
     * 
     * @type {Array<V0OrganizationAppleAPICredentialResponseItem>}
     * @memberof V0OrganizationAppleAPICredentialsListResponse
     */
    data?: Array<V0OrganizationAppleAPICredentialResponseItem>;
}

/**
 * Check if a given object implements the V0OrganizationAppleAPICredentialsListResponse interface.
 */
export function instanceOfV0OrganizationAppleAPICredentialsListResponse(value: object): value is V0OrganizationAppleAPICredentialsListResponse {
    return true;
}

export function V0OrganizationAppleAPICredentialsListResponseFromJSON(json: any): V0OrganizationAppleAPICredentialsListResponse {
    return V0OrganizationAppleAPICredentialsListResponseFromJSONTyped(json, false);
}

export function V0OrganizationAppleAPICredentialsListResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0OrganizationAppleAPICredentialsListResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(V0OrganizationAppleAPICredentialResponseItemFromJSON)),
    };
}

export function V0OrganizationAppleAPICredentialsListResponseToJSON(json: any): V0OrganizationAppleAPICredentialsListResponse {
    return V0OrganizationAppleAPICredentialsListResponseToJSONTyped(json, false);
}

export function V0OrganizationAppleAPICredentialsListResponseToJSONTyped(value?: V0OrganizationAppleAPICredentialsListResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(V0OrganizationAppleAPICredentialResponseItemToJSON)),
    };
}

