/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V0OrganizationAppleAPICredetialCreateResponseItem } from './V0OrganizationAppleAPICredetialCreateResponseItem';
import {
    V0OrganizationAppleAPICredetialCreateResponseItemFromJSON,
    V0OrganizationAppleAPICredetialCreateResponseItemFromJSONTyped,
    V0OrganizationAppleAPICredetialCreateResponseItemToJSON,
    V0OrganizationAppleAPICredetialCreateResponseItemToJSONTyped,
} from './V0OrganizationAppleAPICredetialCreateResponseItem';

/**
 * 
 * @export
 * @interface V0OrganizationAppleAPICredetialCreateResponse
 */
export interface V0OrganizationAppleAPICredetialCreateResponse {
    /**
     * 
     * @type {V0OrganizationAppleAPICredetialCreateResponseItem}
     * @memberof V0OrganizationAppleAPICredetialCreateResponse
     */
    data?: V0OrganizationAppleAPICredetialCreateResponseItem;
}

/**
 * Check if a given object implements the V0OrganizationAppleAPICredetialCreateResponse interface.
 */
export function instanceOfV0OrganizationAppleAPICredetialCreateResponse(value: object): value is V0OrganizationAppleAPICredetialCreateResponse {
    return true;
}

export function V0OrganizationAppleAPICredetialCreateResponseFromJSON(json: any): V0OrganizationAppleAPICredetialCreateResponse {
    return V0OrganizationAppleAPICredetialCreateResponseFromJSONTyped(json, false);
}

export function V0OrganizationAppleAPICredetialCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0OrganizationAppleAPICredetialCreateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : V0OrganizationAppleAPICredetialCreateResponseItemFromJSON(json['data']),
    };
}

export function V0OrganizationAppleAPICredetialCreateResponseToJSON(json: any): V0OrganizationAppleAPICredetialCreateResponse {
    return V0OrganizationAppleAPICredetialCreateResponseToJSONTyped(json, false);
}

export function V0OrganizationAppleAPICredetialCreateResponseToJSONTyped(value?: V0OrganizationAppleAPICredetialCreateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': V0OrganizationAppleAPICredetialCreateResponseItemToJSON(value['data']),
    };
}

