/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V0OrganizationGoogleServiceCredetialCreateResponseItem } from './V0OrganizationGoogleServiceCredetialCreateResponseItem';
import {
    V0OrganizationGoogleServiceCredetialCreateResponseItemFromJSON,
    V0OrganizationGoogleServiceCredetialCreateResponseItemFromJSONTyped,
    V0OrganizationGoogleServiceCredetialCreateResponseItemToJSON,
    V0OrganizationGoogleServiceCredetialCreateResponseItemToJSONTyped,
} from './V0OrganizationGoogleServiceCredetialCreateResponseItem';

/**
 * 
 * @export
 * @interface V0OrganizationGoogleServiceCredetialCreateResponse
 */
export interface V0OrganizationGoogleServiceCredetialCreateResponse {
    /**
     * 
     * @type {V0OrganizationGoogleServiceCredetialCreateResponseItem}
     * @memberof V0OrganizationGoogleServiceCredetialCreateResponse
     */
    data?: V0OrganizationGoogleServiceCredetialCreateResponseItem;
}

/**
 * Check if a given object implements the V0OrganizationGoogleServiceCredetialCreateResponse interface.
 */
export function instanceOfV0OrganizationGoogleServiceCredetialCreateResponse(value: object): value is V0OrganizationGoogleServiceCredetialCreateResponse {
    return true;
}

export function V0OrganizationGoogleServiceCredetialCreateResponseFromJSON(json: any): V0OrganizationGoogleServiceCredetialCreateResponse {
    return V0OrganizationGoogleServiceCredetialCreateResponseFromJSONTyped(json, false);
}

export function V0OrganizationGoogleServiceCredetialCreateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0OrganizationGoogleServiceCredetialCreateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : V0OrganizationGoogleServiceCredetialCreateResponseItemFromJSON(json['data']),
    };
}

export function V0OrganizationGoogleServiceCredetialCreateResponseToJSON(json: any): V0OrganizationGoogleServiceCredetialCreateResponse {
    return V0OrganizationGoogleServiceCredetialCreateResponseToJSONTyped(json, false);
}

export function V0OrganizationGoogleServiceCredetialCreateResponseToJSONTyped(value?: V0OrganizationGoogleServiceCredetialCreateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': V0OrganizationGoogleServiceCredetialCreateResponseItemToJSON(value['data']),
    };
}

