/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V0OwnerAccountResponseModel
 */
export interface V0OwnerAccountResponseModel {
    /**
     * 
     * @type {string}
     * @memberof V0OwnerAccountResponseModel
     */
    accountType?: string;
    /**
     * 
     * @type {string}
     * @memberof V0OwnerAccountResponseModel
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof V0OwnerAccountResponseModel
     */
    slug?: string;
}

/**
 * Check if a given object implements the V0OwnerAccountResponseModel interface.
 */
export function instanceOfV0OwnerAccountResponseModel(value: object): value is V0OwnerAccountResponseModel {
    return true;
}

export function V0OwnerAccountResponseModelFromJSON(json: any): V0OwnerAccountResponseModel {
    return V0OwnerAccountResponseModelFromJSONTyped(json, false);
}

export function V0OwnerAccountResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0OwnerAccountResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'accountType': json['account_type'] == null ? undefined : json['account_type'],
        'name': json['name'] == null ? undefined : json['name'],
        'slug': json['slug'] == null ? undefined : json['slug'],
    };
}

export function V0OwnerAccountResponseModelToJSON(json: any): V0OwnerAccountResponseModel {
    return V0OwnerAccountResponseModelToJSONTyped(json, false);
}

export function V0OwnerAccountResponseModelToJSONTyped(value?: V0OwnerAccountResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'account_type': value['accountType'],
        'name': value['name'],
        'slug': value['slug'],
    };
}

