/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V0OwnerAddOnResponseItemModel } from './V0OwnerAddOnResponseItemModel';
import {
    V0OwnerAddOnResponseItemModelFromJSON,
    V0OwnerAddOnResponseItemModelFromJSONTyped,
    V0OwnerAddOnResponseItemModelToJSON,
    V0OwnerAddOnResponseItemModelToJSONTyped,
} from './V0OwnerAddOnResponseItemModel';

/**
 * 
 * @export
 * @interface V0OwnerAddOnsListResponseModel
 */
export interface V0OwnerAddOnsListResponseModel {
    /**
     * 
     * @type {Array<V0OwnerAddOnResponseItemModel>}
     * @memberof V0OwnerAddOnsListResponseModel
     */
    data?: Array<V0OwnerAddOnResponseItemModel>;
}

/**
 * Check if a given object implements the V0OwnerAddOnsListResponseModel interface.
 */
export function instanceOfV0OwnerAddOnsListResponseModel(value: object): value is V0OwnerAddOnsListResponseModel {
    return true;
}

export function V0OwnerAddOnsListResponseModelFromJSON(json: any): V0OwnerAddOnsListResponseModel {
    return V0OwnerAddOnsListResponseModelFromJSONTyped(json, false);
}

export function V0OwnerAddOnsListResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0OwnerAddOnsListResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(V0OwnerAddOnResponseItemModelFromJSON)),
    };
}

export function V0OwnerAddOnsListResponseModelToJSON(json: any): V0OwnerAddOnsListResponseModel {
    return V0OwnerAddOnsListResponseModelToJSONTyped(json, false);
}

export function V0OwnerAddOnsListResponseModelToJSONTyped(value?: V0OwnerAddOnsListResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(V0OwnerAddOnResponseItemModelToJSON)),
    };
}

