/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V0PagingResponseModel
 */
export interface V0PagingResponseModel {
    /**
     * Next is the "anchor" for pagination. This value should be passed to the same endpoint
     * to get the next page. Empty/not included if there's no "next" page.
     * Stop paging when there's no "Next" item in the response!
     * @type {string}
     * @memberof V0PagingResponseModel
     */
    next?: string;
    /**
     * PageItemLimit - per-page item count. A given page might include
     * less items if there's not enough items. This value is the "max item count per page".
     * @type {number}
     * @memberof V0PagingResponseModel
     */
    pageItemLimit?: number;
    /**
     * TotalItemCount - total item count, through "all pages"
     * @type {number}
     * @memberof V0PagingResponseModel
     */
    totalItemCount?: number;
}

/**
 * Check if a given object implements the V0PagingResponseModel interface.
 */
export function instanceOfV0PagingResponseModel(value: object): value is V0PagingResponseModel {
    return true;
}

export function V0PagingResponseModelFromJSON(json: any): V0PagingResponseModel {
    return V0PagingResponseModelFromJSONTyped(json, false);
}

export function V0PagingResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0PagingResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'next': json['next'] == null ? undefined : json['next'],
        'pageItemLimit': json['page_item_limit'] == null ? undefined : json['page_item_limit'],
        'totalItemCount': json['total_item_count'] == null ? undefined : json['total_item_count'],
    };
}

export function V0PagingResponseModelToJSON(json: any): V0PagingResponseModel {
    return V0PagingResponseModelToJSONTyped(json, false);
}

export function V0PagingResponseModelToJSONTyped(value?: V0PagingResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'next': value['next'],
        'page_item_limit': value['pageItemLimit'],
        'total_item_count': value['totalItemCount'],
    };
}

