/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V0PipelineRebuildParams
 */
export interface V0PipelineRebuildParams {
    /**
     * 
     * @type {boolean}
     * @memberof V0PipelineRebuildParams
     */
    partial?: boolean;
    /**
     * 
     * @type {string}
     * @memberof V0PipelineRebuildParams
     */
    triggeredBy?: string;
}

/**
 * Check if a given object implements the V0PipelineRebuildParams interface.
 */
export function instanceOfV0PipelineRebuildParams(value: object): value is V0PipelineRebuildParams {
    return true;
}

export function V0PipelineRebuildParamsFromJSON(json: any): V0PipelineRebuildParams {
    return V0PipelineRebuildParamsFromJSONTyped(json, false);
}

export function V0PipelineRebuildParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0PipelineRebuildParams {
    if (json == null) {
        return json;
    }
    return {
        
        'partial': json['partial'] == null ? undefined : json['partial'],
        'triggeredBy': json['triggered_by'] == null ? undefined : json['triggered_by'],
    };
}

export function V0PipelineRebuildParamsToJSON(json: any): V0PipelineRebuildParams {
    return V0PipelineRebuildParamsToJSONTyped(json, false);
}

export function V0PipelineRebuildParamsToJSONTyped(value?: V0PipelineRebuildParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'partial': value['partial'],
        'triggered_by': value['triggeredBy'],
    };
}

