/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PipelineabledomainBuildToolInvocation } from './PipelineabledomainBuildToolInvocation';
import {
    PipelineabledomainBuildToolInvocationFromJSON,
    PipelineabledomainBuildToolInvocationFromJSONTyped,
    PipelineabledomainBuildToolInvocationToJSON,
    PipelineabledomainBuildToolInvocationToJSONTyped,
} from './PipelineabledomainBuildToolInvocation';
import type { PipelineabledomainTriggerParams } from './PipelineabledomainTriggerParams';
import {
    PipelineabledomainTriggerParamsFromJSON,
    PipelineabledomainTriggerParamsFromJSONTyped,
    PipelineabledomainTriggerParamsToJSON,
    PipelineabledomainTriggerParamsToJSONTyped,
} from './PipelineabledomainTriggerParams';
import type { PipelineabledomainLocalConfig } from './PipelineabledomainLocalConfig';
import {
    PipelineabledomainLocalConfigFromJSON,
    PipelineabledomainLocalConfigFromJSONTyped,
    PipelineabledomainLocalConfigToJSON,
    PipelineabledomainLocalConfigToJSONTyped,
} from './PipelineabledomainLocalConfig';
import type { PipelineabledomainArtifactMeta } from './PipelineabledomainArtifactMeta';
import {
    PipelineabledomainArtifactMetaFromJSON,
    PipelineabledomainArtifactMetaFromJSONTyped,
    PipelineabledomainArtifactMetaToJSON,
    PipelineabledomainArtifactMetaToJSONTyped,
} from './PipelineabledomainArtifactMeta';

/**
 * 
 * @export
 * @interface V0PipelineListResponseItemModel
 */
export interface V0PipelineListResponseItemModel {
    /**
     * 
     * @type {Array<PipelineabledomainArtifactMeta>}
     * @memberof V0PipelineListResponseItemModel
     */
    artifacts?: Array<PipelineabledomainArtifactMeta>;
    /**
     * 
     * @type {string}
     * @memberof V0PipelineListResponseItemModel
     */
    branch?: string;
    /**
     * 
     * @type {number}
     * @memberof V0PipelineListResponseItemModel
     */
    buildNumber?: number;
    /**
     * 
     * @type {Array<PipelineabledomainBuildToolInvocation>}
     * @memberof V0PipelineListResponseItemModel
     */
    buildToolInvocations?: Array<PipelineabledomainBuildToolInvocation>;
    /**
     * 
     * @type {string}
     * @memberof V0PipelineListResponseItemModel
     */
    commitHash?: string;
    /**
     * 
     * @type {string}
     * @memberof V0PipelineListResponseItemModel
     */
    commitMessage?: string;
    /**
     * 
     * @type {number}
     * @memberof V0PipelineListResponseItemModel
     */
    creditCost?: number;
    /**
     * 
     * @type {string}
     * @memberof V0PipelineListResponseItemModel
     */
    finishedAt?: string;
    /**
     * 
     * @type {boolean}
     * @memberof V0PipelineListResponseItemModel
     */
    isOnHold?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof V0PipelineListResponseItemModel
     */
    isPipeline?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof V0PipelineListResponseItemModel
     */
    isProcessed?: boolean;
    /**
     * 
     * @type {PipelineabledomainLocalConfig}
     * @memberof V0PipelineListResponseItemModel
     */
    localConfig?: PipelineabledomainLocalConfig;
    /**
     * 
     * @type {number}
     * @memberof V0PipelineListResponseItemModel
     */
    pullRequestId?: number;
    /**
     * 
     * @type {string}
     * @memberof V0PipelineListResponseItemModel
     */
    pullRequestTargetBranch?: string;
    /**
     * 
     * @type {boolean}
     * @memberof V0PipelineListResponseItemModel
     */
    rebuildable?: boolean;
    /**
     * 
     * @type {string}
     * @memberof V0PipelineListResponseItemModel
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof V0PipelineListResponseItemModel
     */
    startedAt?: string;
    /**
     * 
     * @type {number}
     * @memberof V0PipelineListResponseItemModel
     */
    status?: number;
    /**
     * 
     * @type {string}
     * @memberof V0PipelineListResponseItemModel
     */
    tag?: string;
    /**
     * 
     * @type {PipelineabledomainTriggerParams}
     * @memberof V0PipelineListResponseItemModel
     */
    triggerParams?: PipelineabledomainTriggerParams;
    /**
     * 
     * @type {string}
     * @memberof V0PipelineListResponseItemModel
     */
    triggeredAt?: string;
    /**
     * 
     * @type {string}
     * @memberof V0PipelineListResponseItemModel
     */
    triggeredBy?: string;
    /**
     * 
     * @type {string}
     * @memberof V0PipelineListResponseItemModel
     */
    triggeredWorkflow?: string;
}

/**
 * Check if a given object implements the V0PipelineListResponseItemModel interface.
 */
export function instanceOfV0PipelineListResponseItemModel(value: object): value is V0PipelineListResponseItemModel {
    return true;
}

export function V0PipelineListResponseItemModelFromJSON(json: any): V0PipelineListResponseItemModel {
    return V0PipelineListResponseItemModelFromJSONTyped(json, false);
}

export function V0PipelineListResponseItemModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0PipelineListResponseItemModel {
    if (json == null) {
        return json;
    }
    return {
        
        'artifacts': json['artifacts'] == null ? undefined : ((json['artifacts'] as Array<any>).map(PipelineabledomainArtifactMetaFromJSON)),
        'branch': json['branch'] == null ? undefined : json['branch'],
        'buildNumber': json['build_number'] == null ? undefined : json['build_number'],
        'buildToolInvocations': json['build_tool_invocations'] == null ? undefined : ((json['build_tool_invocations'] as Array<any>).map(PipelineabledomainBuildToolInvocationFromJSON)),
        'commitHash': json['commit_hash'] == null ? undefined : json['commit_hash'],
        'commitMessage': json['commit_message'] == null ? undefined : json['commit_message'],
        'creditCost': json['credit_cost'] == null ? undefined : json['credit_cost'],
        'finishedAt': json['finished_at'] == null ? undefined : json['finished_at'],
        'isOnHold': json['is_on_hold'] == null ? undefined : json['is_on_hold'],
        'isPipeline': json['is_pipeline'] == null ? undefined : json['is_pipeline'],
        'isProcessed': json['is_processed'] == null ? undefined : json['is_processed'],
        'localConfig': json['local_config'] == null ? undefined : PipelineabledomainLocalConfigFromJSON(json['local_config']),
        'pullRequestId': json['pull_request_id'] == null ? undefined : json['pull_request_id'],
        'pullRequestTargetBranch': json['pull_request_target_branch'] == null ? undefined : json['pull_request_target_branch'],
        'rebuildable': json['rebuildable'] == null ? undefined : json['rebuildable'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'startedAt': json['started_at'] == null ? undefined : json['started_at'],
        'status': json['status'] == null ? undefined : json['status'],
        'tag': json['tag'] == null ? undefined : json['tag'],
        'triggerParams': json['trigger_params'] == null ? undefined : PipelineabledomainTriggerParamsFromJSON(json['trigger_params']),
        'triggeredAt': json['triggered_at'] == null ? undefined : json['triggered_at'],
        'triggeredBy': json['triggered_by'] == null ? undefined : json['triggered_by'],
        'triggeredWorkflow': json['triggered_workflow'] == null ? undefined : json['triggered_workflow'],
    };
}

export function V0PipelineListResponseItemModelToJSON(json: any): V0PipelineListResponseItemModel {
    return V0PipelineListResponseItemModelToJSONTyped(json, false);
}

export function V0PipelineListResponseItemModelToJSONTyped(value?: V0PipelineListResponseItemModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'artifacts': value['artifacts'] == null ? undefined : ((value['artifacts'] as Array<any>).map(PipelineabledomainArtifactMetaToJSON)),
        'branch': value['branch'],
        'build_number': value['buildNumber'],
        'build_tool_invocations': value['buildToolInvocations'] == null ? undefined : ((value['buildToolInvocations'] as Array<any>).map(PipelineabledomainBuildToolInvocationToJSON)),
        'commit_hash': value['commitHash'],
        'commit_message': value['commitMessage'],
        'credit_cost': value['creditCost'],
        'finished_at': value['finishedAt'],
        'is_on_hold': value['isOnHold'],
        'is_pipeline': value['isPipeline'],
        'is_processed': value['isProcessed'],
        'local_config': PipelineabledomainLocalConfigToJSON(value['localConfig']),
        'pull_request_id': value['pullRequestId'],
        'pull_request_target_branch': value['pullRequestTargetBranch'],
        'rebuildable': value['rebuildable'],
        'slug': value['slug'],
        'started_at': value['startedAt'],
        'status': value['status'],
        'tag': value['tag'],
        'trigger_params': PipelineabledomainTriggerParamsToJSON(value['triggerParams']),
        'triggered_at': value['triggeredAt'],
        'triggered_by': value['triggeredBy'],
        'triggered_workflow': value['triggeredWorkflow'],
    };
}

