/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V0AppResponseItemModel } from './V0AppResponseItemModel';
import {
    V0AppResponseItemModelFromJSON,
    V0AppResponseItemModelFromJSONTyped,
    V0AppResponseItemModelToJSON,
    V0AppResponseItemModelToJSONTyped,
} from './V0AppResponseItemModel';

/**
 * 
 * @export
 * @interface V0PipelineListAllResponseItemModel
 */
export interface V0PipelineListAllResponseItemModel {
    /**
     * 
     * @type {string}
     * @memberof V0PipelineListAllResponseItemModel
     */
    branch?: string;
    /**
     * 
     * @type {number}
     * @memberof V0PipelineListAllResponseItemModel
     */
    buildNumber?: number;
    /**
     * 
     * @type {string}
     * @memberof V0PipelineListAllResponseItemModel
     */
    commitHash?: string;
    /**
     * 
     * @type {string}
     * @memberof V0PipelineListAllResponseItemModel
     */
    commitMessage?: string;
    /**
     * 
     * @type {number}
     * @memberof V0PipelineListAllResponseItemModel
     */
    creditCost?: number;
    /**
     * 
     * @type {string}
     * @memberof V0PipelineListAllResponseItemModel
     */
    finishedAt?: string;
    /**
     * 
     * @type {boolean}
     * @memberof V0PipelineListAllResponseItemModel
     */
    isOnHold?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof V0PipelineListAllResponseItemModel
     */
    isPipeline?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof V0PipelineListAllResponseItemModel
     */
    isProcessed?: boolean;
    /**
     * 
     * @type {number}
     * @memberof V0PipelineListAllResponseItemModel
     */
    pullRequestId?: number;
    /**
     * 
     * @type {string}
     * @memberof V0PipelineListAllResponseItemModel
     */
    pullRequestTargetBranch?: string;
    /**
     * 
     * @type {V0AppResponseItemModel}
     * @memberof V0PipelineListAllResponseItemModel
     */
    repository?: V0AppResponseItemModel;
    /**
     * 
     * @type {string}
     * @memberof V0PipelineListAllResponseItemModel
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof V0PipelineListAllResponseItemModel
     */
    startedAt?: string;
    /**
     * 
     * @type {number}
     * @memberof V0PipelineListAllResponseItemModel
     */
    status?: number;
    /**
     * 
     * @type {string}
     * @memberof V0PipelineListAllResponseItemModel
     */
    tag?: string;
    /**
     * 
     * @type {string}
     * @memberof V0PipelineListAllResponseItemModel
     */
    triggeredAt?: string;
    /**
     * 
     * @type {string}
     * @memberof V0PipelineListAllResponseItemModel
     */
    triggeredBy?: string;
    /**
     * 
     * @type {string}
     * @memberof V0PipelineListAllResponseItemModel
     */
    triggeredWorkflow?: string;
}

/**
 * Check if a given object implements the V0PipelineListAllResponseItemModel interface.
 */
export function instanceOfV0PipelineListAllResponseItemModel(value: object): value is V0PipelineListAllResponseItemModel {
    return true;
}

export function V0PipelineListAllResponseItemModelFromJSON(json: any): V0PipelineListAllResponseItemModel {
    return V0PipelineListAllResponseItemModelFromJSONTyped(json, false);
}

export function V0PipelineListAllResponseItemModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0PipelineListAllResponseItemModel {
    if (json == null) {
        return json;
    }
    return {
        
        'branch': json['branch'] == null ? undefined : json['branch'],
        'buildNumber': json['build_number'] == null ? undefined : json['build_number'],
        'commitHash': json['commit_hash'] == null ? undefined : json['commit_hash'],
        'commitMessage': json['commit_message'] == null ? undefined : json['commit_message'],
        'creditCost': json['credit_cost'] == null ? undefined : json['credit_cost'],
        'finishedAt': json['finished_at'] == null ? undefined : json['finished_at'],
        'isOnHold': json['is_on_hold'] == null ? undefined : json['is_on_hold'],
        'isPipeline': json['is_pipeline'] == null ? undefined : json['is_pipeline'],
        'isProcessed': json['is_processed'] == null ? undefined : json['is_processed'],
        'pullRequestId': json['pull_request_id'] == null ? undefined : json['pull_request_id'],
        'pullRequestTargetBranch': json['pull_request_target_branch'] == null ? undefined : json['pull_request_target_branch'],
        'repository': json['repository'] == null ? undefined : V0AppResponseItemModelFromJSON(json['repository']),
        'slug': json['slug'] == null ? undefined : json['slug'],
        'startedAt': json['started_at'] == null ? undefined : json['started_at'],
        'status': json['status'] == null ? undefined : json['status'],
        'tag': json['tag'] == null ? undefined : json['tag'],
        'triggeredAt': json['triggered_at'] == null ? undefined : json['triggered_at'],
        'triggeredBy': json['triggered_by'] == null ? undefined : json['triggered_by'],
        'triggeredWorkflow': json['triggered_workflow'] == null ? undefined : json['triggered_workflow'],
    };
}

export function V0PipelineListAllResponseItemModelToJSON(json: any): V0PipelineListAllResponseItemModel {
    return V0PipelineListAllResponseItemModelToJSONTyped(json, false);
}

export function V0PipelineListAllResponseItemModelToJSONTyped(value?: V0PipelineListAllResponseItemModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'branch': value['branch'],
        'build_number': value['buildNumber'],
        'commit_hash': value['commitHash'],
        'commit_message': value['commitMessage'],
        'credit_cost': value['creditCost'],
        'finished_at': value['finishedAt'],
        'is_on_hold': value['isOnHold'],
        'is_pipeline': value['isPipeline'],
        'is_processed': value['isProcessed'],
        'pull_request_id': value['pullRequestId'],
        'pull_request_target_branch': value['pullRequestTargetBranch'],
        'repository': V0AppResponseItemModelToJSON(value['repository']),
        'slug': value['slug'],
        'started_at': value['startedAt'],
        'status': value['status'],
        'tag': value['tag'],
        'triggered_at': value['triggeredAt'],
        'triggered_by': value['triggeredBy'],
        'triggered_workflow': value['triggeredWorkflow'],
    };
}

