/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V0PipelineShowWorkflowResponseModel } from './V0PipelineShowWorkflowResponseModel';
import {
    V0PipelineShowWorkflowResponseModelFromJSON,
    V0PipelineShowWorkflowResponseModelFromJSONTyped,
    V0PipelineShowWorkflowResponseModelToJSON,
    V0PipelineShowWorkflowResponseModelToJSONTyped,
} from './V0PipelineShowWorkflowResponseModel';

/**
 * 
 * @export
 * @interface V0PipelineShowStageResponseModel
 */
export interface V0PipelineShowStageResponseModel {
    /**
     * 
     * @type {string}
     * @memberof V0PipelineShowStageResponseModel
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof V0PipelineShowStageResponseModel
     */
    name?: string;
    /**
     * 
     * @type {Array<V0PipelineShowWorkflowResponseModel>}
     * @memberof V0PipelineShowStageResponseModel
     */
    workflows?: Array<V0PipelineShowWorkflowResponseModel>;
}

/**
 * Check if a given object implements the V0PipelineShowStageResponseModel interface.
 */
export function instanceOfV0PipelineShowStageResponseModel(value: object): value is V0PipelineShowStageResponseModel {
    return true;
}

export function V0PipelineShowStageResponseModelFromJSON(json: any): V0PipelineShowStageResponseModel {
    return V0PipelineShowStageResponseModelFromJSONTyped(json, false);
}

export function V0PipelineShowStageResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0PipelineShowStageResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'workflows': json['workflows'] == null ? undefined : ((json['workflows'] as Array<any>).map(V0PipelineShowWorkflowResponseModelFromJSON)),
    };
}

export function V0PipelineShowStageResponseModelToJSON(json: any): V0PipelineShowStageResponseModel {
    return V0PipelineShowStageResponseModelToJSONTyped(json, false);
}

export function V0PipelineShowStageResponseModelToJSONTyped(value?: V0PipelineShowStageResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'workflows': value['workflows'] == null ? undefined : ((value['workflows'] as Array<any>).map(V0PipelineShowWorkflowResponseModelToJSON)),
    };
}

