/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V0PipelineShowAppResponseModel
 */
export interface V0PipelineShowAppResponseModel {
    /**
     * 
     * @type {string}
     * @memberof V0PipelineShowAppResponseModel
     */
    slug?: string;
}

/**
 * Check if a given object implements the V0PipelineShowAppResponseModel interface.
 */
export function instanceOfV0PipelineShowAppResponseModel(value: object): value is V0PipelineShowAppResponseModel {
    return true;
}

export function V0PipelineShowAppResponseModelFromJSON(json: any): V0PipelineShowAppResponseModel {
    return V0PipelineShowAppResponseModelFromJSONTyped(json, false);
}

export function V0PipelineShowAppResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0PipelineShowAppResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'slug': json['slug'] == null ? undefined : json['slug'],
    };
}

export function V0PipelineShowAppResponseModelToJSON(json: any): V0PipelineShowAppResponseModel {
    return V0PipelineShowAppResponseModelToJSONTyped(json, false);
}

export function V0PipelineShowAppResponseModelToJSONTyped(value?: V0PipelineShowAppResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'slug': value['slug'],
    };
}

