/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V0PipelineShowEnvironmentsResponseModel
 */
export interface V0PipelineShowEnvironmentsResponseModel {
    /**
     * 
     * @type {boolean}
     * @memberof V0PipelineShowEnvironmentsResponseModel
     */
    isExpand?: boolean;
    /**
     * 
     * @type {string}
     * @memberof V0PipelineShowEnvironmentsResponseModel
     */
    key?: string;
    /**
     * 
     * @type {object}
     * @memberof V0PipelineShowEnvironmentsResponseModel
     */
    value?: object;
}

/**
 * Check if a given object implements the V0PipelineShowEnvironmentsResponseModel interface.
 */
export function instanceOfV0PipelineShowEnvironmentsResponseModel(value: object): value is V0PipelineShowEnvironmentsResponseModel {
    return true;
}

export function V0PipelineShowEnvironmentsResponseModelFromJSON(json: any): V0PipelineShowEnvironmentsResponseModel {
    return V0PipelineShowEnvironmentsResponseModelFromJSONTyped(json, false);
}

export function V0PipelineShowEnvironmentsResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0PipelineShowEnvironmentsResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'isExpand': json['is_expand'] == null ? undefined : json['is_expand'],
        'key': json['key'] == null ? undefined : json['key'],
        'value': json['value'] == null ? undefined : json['value'],
    };
}

export function V0PipelineShowEnvironmentsResponseModelToJSON(json: any): V0PipelineShowEnvironmentsResponseModel {
    return V0PipelineShowEnvironmentsResponseModelToJSONTyped(json, false);
}

export function V0PipelineShowEnvironmentsResponseModelToJSONTyped(value?: V0PipelineShowEnvironmentsResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'is_expand': value['isExpand'],
        'key': value['key'],
        'value': value['value'],
    };
}

