/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V0PipelineShowWorkflowResponseModel } from './V0PipelineShowWorkflowResponseModel';
import {
    V0PipelineShowWorkflowResponseModelFromJSON,
    V0PipelineShowWorkflowResponseModelFromJSONTyped,
    V0PipelineShowWorkflowResponseModelToJSON,
    V0PipelineShowWorkflowResponseModelToJSONTyped,
} from './V0PipelineShowWorkflowResponseModel';
import type { V0PipelineShowStageResponseModel } from './V0PipelineShowStageResponseModel';
import {
    V0PipelineShowStageResponseModelFromJSON,
    V0PipelineShowStageResponseModelFromJSONTyped,
    V0PipelineShowStageResponseModelToJSON,
    V0PipelineShowStageResponseModelToJSONTyped,
} from './V0PipelineShowStageResponseModel';
import type { V0PipelineShowTriggerParamsResponseModel } from './V0PipelineShowTriggerParamsResponseModel';
import {
    V0PipelineShowTriggerParamsResponseModelFromJSON,
    V0PipelineShowTriggerParamsResponseModelFromJSONTyped,
    V0PipelineShowTriggerParamsResponseModelToJSON,
    V0PipelineShowTriggerParamsResponseModelToJSONTyped,
} from './V0PipelineShowTriggerParamsResponseModel';
import type { V0PipelineShowAppResponseModel } from './V0PipelineShowAppResponseModel';
import {
    V0PipelineShowAppResponseModelFromJSON,
    V0PipelineShowAppResponseModelFromJSONTyped,
    V0PipelineShowAppResponseModelToJSON,
    V0PipelineShowAppResponseModelToJSONTyped,
} from './V0PipelineShowAppResponseModel';
import type { V0PipelineShowAttemptResponseModel } from './V0PipelineShowAttemptResponseModel';
import {
    V0PipelineShowAttemptResponseModelFromJSON,
    V0PipelineShowAttemptResponseModelFromJSONTyped,
    V0PipelineShowAttemptResponseModelToJSON,
    V0PipelineShowAttemptResponseModelToJSONTyped,
} from './V0PipelineShowAttemptResponseModel';

/**
 * 
 * @export
 * @interface V0PipelineShowResponseModel
 */
export interface V0PipelineShowResponseModel {
    /**
     * 
     * @type {string}
     * @memberof V0PipelineShowResponseModel
     */
    abortReason?: string;
    /**
     * 
     * @type {V0PipelineShowAppResponseModel}
     * @memberof V0PipelineShowResponseModel
     */
    app?: V0PipelineShowAppResponseModel;
    /**
     * 
     * @type {Array<V0PipelineShowAttemptResponseModel>}
     * @memberof V0PipelineShowResponseModel
     */
    attempts?: Array<V0PipelineShowAttemptResponseModel>;
    /**
     * 
     * @type {object}
     * @memberof V0PipelineShowResponseModel
     */
    creditCost?: object;
    /**
     * 
     * @type {string}
     * @memberof V0PipelineShowResponseModel
     */
    currentAttemptId?: string;
    /**
     * 
     * @type {string}
     * @memberof V0PipelineShowResponseModel
     */
    finishedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof V0PipelineShowResponseModel
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof V0PipelineShowResponseModel
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof V0PipelineShowResponseModel
     */
    numberInAppScope?: number;
    /**
     * 
     * @type {object}
     * @memberof V0PipelineShowResponseModel
     */
    putOnHoldAt?: object;
    /**
     * 
     * @type {boolean}
     * @memberof V0PipelineShowResponseModel
     */
    rebuildable?: boolean;
    /**
     * 
     * @type {Array<V0PipelineShowStageResponseModel>}
     * @memberof V0PipelineShowResponseModel
     */
    stages?: Array<V0PipelineShowStageResponseModel>;
    /**
     * 
     * @type {string}
     * @memberof V0PipelineShowResponseModel
     */
    startedAt?: string;
    /**
     * 
     * @type {string}
     * @memberof V0PipelineShowResponseModel
     */
    status?: V0PipelineShowResponseModelStatusEnum;
    /**
     * 
     * @type {V0PipelineShowTriggerParamsResponseModel}
     * @memberof V0PipelineShowResponseModel
     */
    triggerParams?: V0PipelineShowTriggerParamsResponseModel;
    /**
     * 
     * @type {string}
     * @memberof V0PipelineShowResponseModel
     */
    triggeredAt?: string;
    /**
     * 
     * @type {string}
     * @memberof V0PipelineShowResponseModel
     */
    triggeredBy?: string;
    /**
     * 
     * @type {string}
     * @memberof V0PipelineShowResponseModel
     */
    type?: string;
    /**
     * 
     * @type {Array<V0PipelineShowWorkflowResponseModel>}
     * @memberof V0PipelineShowResponseModel
     */
    workflows?: Array<V0PipelineShowWorkflowResponseModel>;
}


/**
 * @export
 */
export const V0PipelineShowResponseModelStatusEnum = {
    Aborted: 'aborted',
    Failed: 'failed',
    Initializing: 'initializing',
    OnHold: 'on_hold',
    Running: 'running',
    Succeeded: 'succeeded',
    SucceededWithAbort: 'succeeded_with_abort'
} as const;
export type V0PipelineShowResponseModelStatusEnum = typeof V0PipelineShowResponseModelStatusEnum[keyof typeof V0PipelineShowResponseModelStatusEnum];


/**
 * Check if a given object implements the V0PipelineShowResponseModel interface.
 */
export function instanceOfV0PipelineShowResponseModel(value: object): value is V0PipelineShowResponseModel {
    return true;
}

export function V0PipelineShowResponseModelFromJSON(json: any): V0PipelineShowResponseModel {
    return V0PipelineShowResponseModelFromJSONTyped(json, false);
}

export function V0PipelineShowResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0PipelineShowResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'abortReason': json['abort_reason'] == null ? undefined : json['abort_reason'],
        'app': json['app'] == null ? undefined : V0PipelineShowAppResponseModelFromJSON(json['app']),
        'attempts': json['attempts'] == null ? undefined : ((json['attempts'] as Array<any>).map(V0PipelineShowAttemptResponseModelFromJSON)),
        'creditCost': json['credit_cost'] == null ? undefined : json['credit_cost'],
        'currentAttemptId': json['current_attempt_id'] == null ? undefined : json['current_attempt_id'],
        'finishedAt': json['finished_at'] == null ? undefined : json['finished_at'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'numberInAppScope': json['number_in_app_scope'] == null ? undefined : json['number_in_app_scope'],
        'putOnHoldAt': json['put_on_hold_at'] == null ? undefined : json['put_on_hold_at'],
        'rebuildable': json['rebuildable'] == null ? undefined : json['rebuildable'],
        'stages': json['stages'] == null ? undefined : ((json['stages'] as Array<any>).map(V0PipelineShowStageResponseModelFromJSON)),
        'startedAt': json['started_at'] == null ? undefined : json['started_at'],
        'status': json['status'] == null ? undefined : json['status'],
        'triggerParams': json['trigger_params'] == null ? undefined : V0PipelineShowTriggerParamsResponseModelFromJSON(json['trigger_params']),
        'triggeredAt': json['triggered_at'] == null ? undefined : json['triggered_at'],
        'triggeredBy': json['triggered_by'] == null ? undefined : json['triggered_by'],
        'type': json['type'] == null ? undefined : json['type'],
        'workflows': json['workflows'] == null ? undefined : ((json['workflows'] as Array<any>).map(V0PipelineShowWorkflowResponseModelFromJSON)),
    };
}

export function V0PipelineShowResponseModelToJSON(json: any): V0PipelineShowResponseModel {
    return V0PipelineShowResponseModelToJSONTyped(json, false);
}

export function V0PipelineShowResponseModelToJSONTyped(value?: V0PipelineShowResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'abort_reason': value['abortReason'],
        'app': V0PipelineShowAppResponseModelToJSON(value['app']),
        'attempts': value['attempts'] == null ? undefined : ((value['attempts'] as Array<any>).map(V0PipelineShowAttemptResponseModelToJSON)),
        'credit_cost': value['creditCost'],
        'current_attempt_id': value['currentAttemptId'],
        'finished_at': value['finishedAt'],
        'id': value['id'],
        'name': value['name'],
        'number_in_app_scope': value['numberInAppScope'],
        'put_on_hold_at': value['putOnHoldAt'],
        'rebuildable': value['rebuildable'],
        'stages': value['stages'] == null ? undefined : ((value['stages'] as Array<any>).map(V0PipelineShowStageResponseModelToJSON)),
        'started_at': value['startedAt'],
        'status': value['status'],
        'trigger_params': V0PipelineShowTriggerParamsResponseModelToJSON(value['triggerParams']),
        'triggered_at': value['triggeredAt'],
        'triggered_by': value['triggeredBy'],
        'type': value['type'],
        'workflows': value['workflows'] == null ? undefined : ((value['workflows'] as Array<any>).map(V0PipelineShowWorkflowResponseModelToJSON)),
    };
}

