/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V0ProjectFileStorageResponseItemModel } from './V0ProjectFileStorageResponseItemModel';
import {
    V0ProjectFileStorageResponseItemModelFromJSON,
    V0ProjectFileStorageResponseItemModelFromJSONTyped,
    V0ProjectFileStorageResponseItemModelToJSON,
    V0ProjectFileStorageResponseItemModelToJSONTyped,
} from './V0ProjectFileStorageResponseItemModel';

/**
 * 
 * @export
 * @interface V0ProjectFileStorageResponseModel
 */
export interface V0ProjectFileStorageResponseModel {
    /**
     * 
     * @type {V0ProjectFileStorageResponseItemModel}
     * @memberof V0ProjectFileStorageResponseModel
     */
    data?: V0ProjectFileStorageResponseItemModel;
}

/**
 * Check if a given object implements the V0ProjectFileStorageResponseModel interface.
 */
export function instanceOfV0ProjectFileStorageResponseModel(value: object): value is V0ProjectFileStorageResponseModel {
    return true;
}

export function V0ProjectFileStorageResponseModelFromJSON(json: any): V0ProjectFileStorageResponseModel {
    return V0ProjectFileStorageResponseModelFromJSONTyped(json, false);
}

export function V0ProjectFileStorageResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0ProjectFileStorageResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : V0ProjectFileStorageResponseItemModelFromJSON(json['data']),
    };
}

export function V0ProjectFileStorageResponseModelToJSON(json: any): V0ProjectFileStorageResponseModel {
    return V0ProjectFileStorageResponseModelToJSONTyped(json, false);
}

export function V0ProjectFileStorageResponseModelToJSONTyped(value?: V0ProjectFileStorageResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': V0ProjectFileStorageResponseItemModelToJSON(value['data']),
    };
}

