/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V0ProjectFileStorageDownloadResponseItemModel } from './V0ProjectFileStorageDownloadResponseItemModel';
import {
    V0ProjectFileStorageDownloadResponseItemModelFromJSON,
    V0ProjectFileStorageDownloadResponseItemModelFromJSONTyped,
    V0ProjectFileStorageDownloadResponseItemModelToJSON,
    V0ProjectFileStorageDownloadResponseItemModelToJSONTyped,
} from './V0ProjectFileStorageDownloadResponseItemModel';

/**
 * 
 * @export
 * @interface V0ProjectFileStorageDownloadResponseModel
 */
export interface V0ProjectFileStorageDownloadResponseModel {
    /**
     * 
     * @type {V0ProjectFileStorageDownloadResponseItemModel}
     * @memberof V0ProjectFileStorageDownloadResponseModel
     */
    data?: V0ProjectFileStorageDownloadResponseItemModel;
}

/**
 * Check if a given object implements the V0ProjectFileStorageDownloadResponseModel interface.
 */
export function instanceOfV0ProjectFileStorageDownloadResponseModel(value: object): value is V0ProjectFileStorageDownloadResponseModel {
    return true;
}

export function V0ProjectFileStorageDownloadResponseModelFromJSON(json: any): V0ProjectFileStorageDownloadResponseModel {
    return V0ProjectFileStorageDownloadResponseModelFromJSONTyped(json, false);
}

export function V0ProjectFileStorageDownloadResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0ProjectFileStorageDownloadResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : V0ProjectFileStorageDownloadResponseItemModelFromJSON(json['data']),
    };
}

export function V0ProjectFileStorageDownloadResponseModelToJSON(json: any): V0ProjectFileStorageDownloadResponseModel {
    return V0ProjectFileStorageDownloadResponseModelToJSONTyped(json, false);
}

export function V0ProjectFileStorageDownloadResponseModelToJSONTyped(value?: V0ProjectFileStorageDownloadResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': V0ProjectFileStorageDownloadResponseItemModelToJSON(value['data']),
    };
}

