/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V0ProvisionProfileUploadResponseItemModel } from './V0ProvisionProfileUploadResponseItemModel';
import {
    V0ProvisionProfileUploadResponseItemModelFromJSON,
    V0ProvisionProfileUploadResponseItemModelFromJSONTyped,
    V0ProvisionProfileUploadResponseItemModelToJSON,
    V0ProvisionProfileUploadResponseItemModelToJSONTyped,
} from './V0ProvisionProfileUploadResponseItemModel';

/**
 * 
 * @export
 * @interface V0ProvisionProfileUploadResponseModel
 */
export interface V0ProvisionProfileUploadResponseModel {
    /**
     * 
     * @type {V0ProvisionProfileUploadResponseItemModel}
     * @memberof V0ProvisionProfileUploadResponseModel
     */
    data?: V0ProvisionProfileUploadResponseItemModel;
}

/**
 * Check if a given object implements the V0ProvisionProfileUploadResponseModel interface.
 */
export function instanceOfV0ProvisionProfileUploadResponseModel(value: object): value is V0ProvisionProfileUploadResponseModel {
    return true;
}

export function V0ProvisionProfileUploadResponseModelFromJSON(json: any): V0ProvisionProfileUploadResponseModel {
    return V0ProvisionProfileUploadResponseModelFromJSONTyped(json, false);
}

export function V0ProvisionProfileUploadResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0ProvisionProfileUploadResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : V0ProvisionProfileUploadResponseItemModelFromJSON(json['data']),
    };
}

export function V0ProvisionProfileUploadResponseModelToJSON(json: any): V0ProvisionProfileUploadResponseModel {
    return V0ProvisionProfileUploadResponseModelToJSONTyped(json, false);
}

export function V0ProvisionProfileUploadResponseModelToJSONTyped(value?: V0ProvisionProfileUploadResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': V0ProvisionProfileUploadResponseItemModelToJSON(value['data']),
    };
}

