/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V0ProvisionProfileResponseItemModel } from './V0ProvisionProfileResponseItemModel';
import {
    V0ProvisionProfileResponseItemModelFromJSON,
    V0ProvisionProfileResponseItemModelFromJSONTyped,
    V0ProvisionProfileResponseItemModelToJSON,
    V0ProvisionProfileResponseItemModelToJSONTyped,
} from './V0ProvisionProfileResponseItemModel';
import type { V0PagingResponseModel } from './V0PagingResponseModel';
import {
    V0PagingResponseModelFromJSON,
    V0PagingResponseModelFromJSONTyped,
    V0PagingResponseModelToJSON,
    V0PagingResponseModelToJSONTyped,
} from './V0PagingResponseModel';

/**
 * 
 * @export
 * @interface V0ProvisionProfileListResponseModel
 */
export interface V0ProvisionProfileListResponseModel {
    /**
     * 
     * @type {Array<V0ProvisionProfileResponseItemModel>}
     * @memberof V0ProvisionProfileListResponseModel
     */
    data?: Array<V0ProvisionProfileResponseItemModel>;
    /**
     * pagination
     * @type {V0PagingResponseModel}
     * @memberof V0ProvisionProfileListResponseModel
     */
    paging?: V0PagingResponseModel;
}

/**
 * Check if a given object implements the V0ProvisionProfileListResponseModel interface.
 */
export function instanceOfV0ProvisionProfileListResponseModel(value: object): value is V0ProvisionProfileListResponseModel {
    return true;
}

export function V0ProvisionProfileListResponseModelFromJSON(json: any): V0ProvisionProfileListResponseModel {
    return V0ProvisionProfileListResponseModelFromJSONTyped(json, false);
}

export function V0ProvisionProfileListResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0ProvisionProfileListResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(V0ProvisionProfileResponseItemModelFromJSON)),
        'paging': json['paging'] == null ? undefined : V0PagingResponseModelFromJSON(json['paging']),
    };
}

export function V0ProvisionProfileListResponseModelToJSON(json: any): V0ProvisionProfileListResponseModel {
    return V0ProvisionProfileListResponseModelToJSONTyped(json, false);
}

export function V0ProvisionProfileListResponseModelToJSONTyped(value?: V0ProvisionProfileListResponseModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(V0ProvisionProfileResponseItemModelToJSON)),
        'paging': V0PagingResponseModelToJSON(value['paging']),
    };
}

