/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V0ProjectFileStorageDownloadResponseItemModel
 */
export interface V0ProjectFileStorageDownloadResponseItemModel {
    /**
     * 
     * @type {string}
     * @memberof V0ProjectFileStorageDownloadResponseItemModel
     */
    downloadUrl?: string;
    /**
     * 
     * @type {object}
     * @memberof V0ProjectFileStorageDownloadResponseItemModel
     */
    exposedMetaDatastore?: object;
    /**
     * 
     * @type {boolean}
     * @memberof V0ProjectFileStorageDownloadResponseItemModel
     */
    isExpose?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof V0ProjectFileStorageDownloadResponseItemModel
     */
    isProtected?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof V0ProjectFileStorageDownloadResponseItemModel
     */
    processed?: boolean;
    /**
     * 
     * @type {string}
     * @memberof V0ProjectFileStorageDownloadResponseItemModel
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof V0ProjectFileStorageDownloadResponseItemModel
     */
    uploadFileName?: string;
    /**
     * 
     * @type {number}
     * @memberof V0ProjectFileStorageDownloadResponseItemModel
     */
    uploadFileSize?: number;
    /**
     * 
     * @type {string}
     * @memberof V0ProjectFileStorageDownloadResponseItemModel
     */
    userEnvKey?: string;
}

/**
 * Check if a given object implements the V0ProjectFileStorageDownloadResponseItemModel interface.
 */
export function instanceOfV0ProjectFileStorageDownloadResponseItemModel(value: object): value is V0ProjectFileStorageDownloadResponseItemModel {
    return true;
}

export function V0ProjectFileStorageDownloadResponseItemModelFromJSON(json: any): V0ProjectFileStorageDownloadResponseItemModel {
    return V0ProjectFileStorageDownloadResponseItemModelFromJSONTyped(json, false);
}

export function V0ProjectFileStorageDownloadResponseItemModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0ProjectFileStorageDownloadResponseItemModel {
    if (json == null) {
        return json;
    }
    return {
        
        'downloadUrl': json['download_url'] == null ? undefined : json['download_url'],
        'exposedMetaDatastore': json['exposed_meta_datastore'] == null ? undefined : json['exposed_meta_datastore'],
        'isExpose': json['is_expose'] == null ? undefined : json['is_expose'],
        'isProtected': json['is_protected'] == null ? undefined : json['is_protected'],
        'processed': json['processed'] == null ? undefined : json['processed'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'uploadFileName': json['upload_file_name'] == null ? undefined : json['upload_file_name'],
        'uploadFileSize': json['upload_file_size'] == null ? undefined : json['upload_file_size'],
        'userEnvKey': json['user_env_key'] == null ? undefined : json['user_env_key'],
    };
}

export function V0ProjectFileStorageDownloadResponseItemModelToJSON(json: any): V0ProjectFileStorageDownloadResponseItemModel {
    return V0ProjectFileStorageDownloadResponseItemModelToJSONTyped(json, false);
}

export function V0ProjectFileStorageDownloadResponseItemModelToJSONTyped(value?: V0ProjectFileStorageDownloadResponseItemModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'download_url': value['downloadUrl'],
        'exposed_meta_datastore': value['exposedMetaDatastore'],
        'is_expose': value['isExpose'],
        'is_protected': value['isProtected'],
        'processed': value['processed'],
        'slug': value['slug'],
        'upload_file_name': value['uploadFileName'],
        'upload_file_size': value['uploadFileSize'],
        'user_env_key': value['userEnvKey'],
    };
}

