/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V0ProvisionProfileUploadResponseItemModel
 */
export interface V0ProvisionProfileUploadResponseItemModel {
    /**
     * 
     * @type {boolean}
     * @memberof V0ProvisionProfileUploadResponseItemModel
     */
    isExpose?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof V0ProvisionProfileUploadResponseItemModel
     */
    isProtected?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof V0ProvisionProfileUploadResponseItemModel
     */
    processed?: boolean;
    /**
     * 
     * @type {string}
     * @memberof V0ProvisionProfileUploadResponseItemModel
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof V0ProvisionProfileUploadResponseItemModel
     */
    uploadFileName?: string;
    /**
     * 
     * @type {number}
     * @memberof V0ProvisionProfileUploadResponseItemModel
     */
    uploadFileSize?: number;
    /**
     * 
     * @type {string}
     * @memberof V0ProvisionProfileUploadResponseItemModel
     */
    uploadUrl?: string;
}

/**
 * Check if a given object implements the V0ProvisionProfileUploadResponseItemModel interface.
 */
export function instanceOfV0ProvisionProfileUploadResponseItemModel(value: object): value is V0ProvisionProfileUploadResponseItemModel {
    return true;
}

export function V0ProvisionProfileUploadResponseItemModelFromJSON(json: any): V0ProvisionProfileUploadResponseItemModel {
    return V0ProvisionProfileUploadResponseItemModelFromJSONTyped(json, false);
}

export function V0ProvisionProfileUploadResponseItemModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0ProvisionProfileUploadResponseItemModel {
    if (json == null) {
        return json;
    }
    return {
        
        'isExpose': json['is_expose'] == null ? undefined : json['is_expose'],
        'isProtected': json['is_protected'] == null ? undefined : json['is_protected'],
        'processed': json['processed'] == null ? undefined : json['processed'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'uploadFileName': json['upload_file_name'] == null ? undefined : json['upload_file_name'],
        'uploadFileSize': json['upload_file_size'] == null ? undefined : json['upload_file_size'],
        'uploadUrl': json['upload_url'] == null ? undefined : json['upload_url'],
    };
}

export function V0ProvisionProfileUploadResponseItemModelToJSON(json: any): V0ProvisionProfileUploadResponseItemModel {
    return V0ProvisionProfileUploadResponseItemModelToJSONTyped(json, false);
}

export function V0ProvisionProfileUploadResponseItemModelToJSONTyped(value?: V0ProvisionProfileUploadResponseItemModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'is_expose': value['isExpose'],
        'is_protected': value['isProtected'],
        'processed': value['processed'],
        'slug': value['slug'],
        'upload_file_name': value['uploadFileName'],
        'upload_file_size': value['uploadFileSize'],
        'upload_url': value['uploadUrl'],
    };
}

