/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V0ProvProfileDocumentUpdateParams
 */
export interface V0ProvProfileDocumentUpdateParams {
    /**
     * 
     * @type {boolean}
     * @memberof V0ProvProfileDocumentUpdateParams
     */
    isExpose?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof V0ProvProfileDocumentUpdateParams
     */
    isProtected?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof V0ProvProfileDocumentUpdateParams
     */
    processed?: boolean;
}

/**
 * Check if a given object implements the V0ProvProfileDocumentUpdateParams interface.
 */
export function instanceOfV0ProvProfileDocumentUpdateParams(value: object): value is V0ProvProfileDocumentUpdateParams {
    return true;
}

export function V0ProvProfileDocumentUpdateParamsFromJSON(json: any): V0ProvProfileDocumentUpdateParams {
    return V0ProvProfileDocumentUpdateParamsFromJSONTyped(json, false);
}

export function V0ProvProfileDocumentUpdateParamsFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0ProvProfileDocumentUpdateParams {
    if (json == null) {
        return json;
    }
    return {
        
        'isExpose': json['is_expose'] == null ? undefined : json['is_expose'],
        'isProtected': json['is_protected'] == null ? undefined : json['is_protected'],
        'processed': json['processed'] == null ? undefined : json['processed'],
    };
}

export function V0ProvProfileDocumentUpdateParamsToJSON(json: any): V0ProvProfileDocumentUpdateParams {
    return V0ProvProfileDocumentUpdateParamsToJSONTyped(json, false);
}

export function V0ProvProfileDocumentUpdateParamsToJSONTyped(value?: V0ProvProfileDocumentUpdateParams | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'is_expose': value['isExpose'],
        'is_protected': value['isProtected'],
        'processed': value['processed'],
    };
}

