/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V0SSHKeyRespModel
 */
export interface V0SSHKeyRespModel {
    /**
     * 
     * @type {string}
     * @memberof V0SSHKeyRespModel
     */
    status?: string;
}

/**
 * Check if a given object implements the V0SSHKeyRespModel interface.
 */
export function instanceOfV0SSHKeyRespModel(value: object): value is V0SSHKeyRespModel {
    return true;
}

export function V0SSHKeyRespModelFromJSON(json: any): V0SSHKeyRespModel {
    return V0SSHKeyRespModelFromJSONTyped(json, false);
}

export function V0SSHKeyRespModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0SSHKeyRespModel {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function V0SSHKeyRespModelToJSON(json: any): V0SSHKeyRespModel {
    return V0SSHKeyRespModelToJSONTyped(json, false);
}

export function V0SSHKeyRespModelToJSONTyped(value?: V0SSHKeyRespModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
    };
}

