/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V0UserProfileDataModel
 */
export interface V0UserProfileDataModel {
    /**
     * 
     * @type {string}
     * @memberof V0UserProfileDataModel
     */
    avatarUrl?: string;
    /**
     * 
     * @type {string}
     * @memberof V0UserProfileDataModel
     */
    createdAt?: string;
    /**
     * 
     * @type {number}
     * @memberof V0UserProfileDataModel
     */
    dataId?: number;
    /**
     * 
     * @type {string}
     * @memberof V0UserProfileDataModel
     */
    email?: string;
    /**
     * 
     * @type {boolean}
     * @memberof V0UserProfileDataModel
     */
    hasUsedOrganizationTrial?: boolean;
    /**
     * 
     * @type {string}
     * @memberof V0UserProfileDataModel
     */
    paymentProcessor?: string;
    /**
     * 
     * @type {string}
     * @memberof V0UserProfileDataModel
     */
    slug?: string;
    /**
     * 
     * @type {string}
     * @memberof V0UserProfileDataModel
     */
    unconfirmedEmail?: string;
    /**
     * 
     * @type {string}
     * @memberof V0UserProfileDataModel
     */
    username?: string;
}

/**
 * Check if a given object implements the V0UserProfileDataModel interface.
 */
export function instanceOfV0UserProfileDataModel(value: object): value is V0UserProfileDataModel {
    return true;
}

export function V0UserProfileDataModelFromJSON(json: any): V0UserProfileDataModel {
    return V0UserProfileDataModelFromJSONTyped(json, false);
}

export function V0UserProfileDataModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0UserProfileDataModel {
    if (json == null) {
        return json;
    }
    return {
        
        'avatarUrl': json['avatar_url'] == null ? undefined : json['avatar_url'],
        'createdAt': json['created_at'] == null ? undefined : json['created_at'],
        'dataId': json['data_id'] == null ? undefined : json['data_id'],
        'email': json['email'] == null ? undefined : json['email'],
        'hasUsedOrganizationTrial': json['has_used_organization_trial'] == null ? undefined : json['has_used_organization_trial'],
        'paymentProcessor': json['payment_processor'] == null ? undefined : json['payment_processor'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'unconfirmedEmail': json['unconfirmed_email'] == null ? undefined : json['unconfirmed_email'],
        'username': json['username'] == null ? undefined : json['username'],
    };
}

export function V0UserProfileDataModelToJSON(json: any): V0UserProfileDataModel {
    return V0UserProfileDataModelToJSONTyped(json, false);
}

export function V0UserProfileDataModelToJSONTyped(value?: V0UserProfileDataModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'avatar_url': value['avatarUrl'],
        'created_at': value['createdAt'],
        'data_id': value['dataId'],
        'email': value['email'],
        'has_used_organization_trial': value['hasUsedOrganizationTrial'],
        'payment_processor': value['paymentProcessor'],
        'slug': value['slug'],
        'unconfirmed_email': value['unconfirmedEmail'],
        'username': value['username'],
    };
}

