/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { V0UserProfileDataModel } from './V0UserProfileDataModel';
import {
    V0UserProfileDataModelFromJSON,
    V0UserProfileDataModelFromJSONTyped,
    V0UserProfileDataModelToJSON,
    V0UserProfileDataModelToJSONTyped,
} from './V0UserProfileDataModel';

/**
 * 
 * @export
 * @interface V0UserProfileRespModel
 */
export interface V0UserProfileRespModel {
    /**
     * 
     * @type {V0UserProfileDataModel}
     * @memberof V0UserProfileRespModel
     */
    data?: V0UserProfileDataModel;
}

/**
 * Check if a given object implements the V0UserProfileRespModel interface.
 */
export function instanceOfV0UserProfileRespModel(value: object): value is V0UserProfileRespModel {
    return true;
}

export function V0UserProfileRespModelFromJSON(json: any): V0UserProfileRespModel {
    return V0UserProfileRespModelFromJSONTyped(json, false);
}

export function V0UserProfileRespModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0UserProfileRespModel {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : V0UserProfileDataModelFromJSON(json['data']),
    };
}

export function V0UserProfileRespModelToJSON(json: any): V0UserProfileRespModel {
    return V0UserProfileRespModelToJSONTyped(json, false);
}

export function V0UserProfileRespModelToJSONTyped(value?: V0UserProfileRespModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': V0UserProfileDataModelToJSON(value['data']),
    };
}

