/* tslint:disable */
/* eslint-disable */
/**
 * Bitrise API
 * Official REST API for Bitrise.io
 *
 * The version of the OpenAPI document: 0.1
 * Contact: letsconnect@bitrise.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface V0WebhookRespModel
 */
export interface V0WebhookRespModel {
    /**
     * 
     * @type {string}
     * @memberof V0WebhookRespModel
     */
    status?: string;
}

/**
 * Check if a given object implements the V0WebhookRespModel interface.
 */
export function instanceOfV0WebhookRespModel(value: object): value is V0WebhookRespModel {
    return true;
}

export function V0WebhookRespModelFromJSON(json: any): V0WebhookRespModel {
    return V0WebhookRespModelFromJSONTyped(json, false);
}

export function V0WebhookRespModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): V0WebhookRespModel {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function V0WebhookRespModelToJSON(json: any): V0WebhookRespModel {
    return V0WebhookRespModelToJSONTyped(json, false);
}

export function V0WebhookRespModelToJSONTyped(value?: V0WebhookRespModel | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
    };
}

